#include "RooRealVar.h"
#include "RooDataSet.h"
#include "RooGaussian.h"
#include "RooChebychev.h"
#include "RooAddPdf.h"
#include "RooWorkspace.h"
#include "RooPlot.h"
#include "TCanvas.h"
#include "TAxis.h"
#include "TFile.h"
#include "TH1.h"
using namespace RooFit;
 
void rs06_Combined_Multiple()
{
   // S e t u p   t h e   F r a m e   f o r   t h e   P l o t
   //------------------------------------------------------------
   TCanvas *c = new TCanvas("fit", "fit", 650, 700);
   TPad *pad1 = new TPad("pad1","pad1",0,0.25,1,1);
   TPad *pad2 = new TPad("pad2","pad2",0,0,1,0.25);
   pad1->SetTopMargin(0.05);
   pad1->SetBottomMargin(0.05);
   pad1->SetLeftMargin(0.15);
   pad1->SetRightMargin(0.05);
   pad2->SetLeftMargin(0.15);
   pad2->SetRightMargin(0.05);
   pad2->SetTopMargin(0.01);
   pad2->SetBottomMargin(0.4);
   // pad2->SetBorderMode(0);
   pad1->Draw();
   pad2->Draw();
   pad1->cd();
   gStyle->SetOptStat(0);
   //=========================================================================================================================================================================//
   // R e a d   w o r k s p a c e   f r o m   f i l e
   // -----------------------------------------------
   // Open input file with workspace (generated by rf503_wspacewrite)
   TFile *f_S = new TFile("/home/belle2/amubarak/Ds2D0enue_Analysis/05-ROOT/Roofit_Suggestion/Fit_Parameter/rs00_SignalPara.root");
   TFile *f_DstarP = new TFile("/home/belle2/amubarak/Ds2D0enue_Analysis/05-ROOT/Roofit_Suggestion/Fit_Parameter/rs01_DstarP.root");
   TFile *f_Dstar0 = new TFile("/home/belle2/amubarak/Ds2D0enue_Analysis/05-ROOT/Roofit_Suggestion/Fit_Parameter/rs02_Dstar0.root");
   TFile *f_D0 = new TFile("/home/belle2/amubarak/Ds2D0enue_Analysis/05-ROOT/Roofit_Suggestion/Fit_Parameter/rs03_D0.root");
   TFile *f_O = new TFile("/home/belle2/amubarak/Ds2D0enue_Analysis/05-ROOT/Roofit_Suggestion/Fit_Parameter/rs04_OtherPara.root");
 
   // R e t r i e v e   p d f   f r o m   w o r k s p a c e
   // -----------------------------------------------------------------
   // Signal
   RooWorkspace *w_S = (RooWorkspace *)f_S->Get("w_S");
   // RooRealVar *M_S = w_S->var("Ds_diff_D0pi");
   RooAbsPdf *SignalModel = w_S->pdf("SignalModel");

   // Peaking Background
   RooWorkspace *w_DstarP = (RooWorkspace *)f_DstarP->Get("w_PBkg");
   // RooRealVar *M_PBkg = w_PBkg->var("Ds_diff_D0pi");
   RooAbsPdf *DstarPModel = w_DstarP->pdf("DstarPModel");

   // Combinatorial + Failed Background
   RooWorkspace *w_Dstar0 = (RooWorkspace *)f_Dstar0->Get("w_Dstar0");
   // RooRealVar *M_CFBkg = w_CFBkg->var("Ds_diff_D0pi");
   RooAbsPdf *Dstar0BkgModel = w_Dstar0->pdf("Dstar0BkgModel");

   // Fake Signal
   RooWorkspace *w_D0 = (RooWorkspace *)f_D0->Get("w_D0");
   // RooRealVar *M_CFBkg = w_CFBkg->var("Ds_diff_D0pi");
   RooAbsPdf *D0BkgModel = w_D0->pdf("D0BkgModel");

   // Other
   RooWorkspace *w_O = (RooWorkspace *)f_O->Get("w_O");
   // RooRealVar *M_OBkg = w_CFBkg->var("Ds_diff_D0pi");
   RooAbsPdf *OtherModel = w_O->pdf("OtherModel");

   w_S->loadSnapshot("reference_fit_Signal");
   w_DstarP->loadSnapshot("reference_fit_PeakingBkg");
   w_Dstar0->loadSnapshot("reference_fit_Dstar0_Bkg");
   w_D0->loadSnapshot("reference_fit_D0");
   w_O->loadSnapshot("reference_fit_Other");
   //=========================================================================================================================================================================//
   // I n i t i a l i z a t i o n:
   // --------------------------------------------------------------
   // The lines below initializes all my values
   int bin = 50;
   double xL = 0.1;
   double xR = 0.55;
   //=========================================================================================================================================================================//
   // I m p o r t s   D a t a   f r o m   t r e e   b r a n c h:
   // --------------------------------------------------------------
   // Total Viewing
   // TFile *file = new TFile("/group/belle2/users2022/amubarak/02-Grid/Completed_TopoAna/Ds2D0e-Generic_Ds_021325_2_ccbar.root");
   // TTree *tree = (TTree*)file->Get("Dstree");
   // Individual Viewing
   TFile *file = new TFile("/home/belle2/amubarak/C03-Grid/TopoAna.root");
   TTree *tree_1 = (TTree*)file->Get("Dstarplus");
   TTree *tree_2 = (TTree*)file->Get("Dstar0");
   TTree *tree_3 = (TTree*)file->Get("D0");
   TTree *tree_4 = (TTree*)file->Get("FakeD0");
   //=========================================================================================================================================================================//
   // D a t a:
   // --------------------------------------------------------------
   RooRealVar DeltaM("Ds_diff_D0pi", "Mass Difference", xL, xR);
   RooRealVar BS("Ds_extraInfo_BkgBDT", "Background Suppression", 0.0, 1.0);

   RooDataSet data_1("data_1", "dataset with mass (1)", tree_1, RooArgSet(DeltaM,BS));
   RooDataSet data_2("data_2", "dataset with mass (2)", tree_2, RooArgSet(DeltaM,BS));
   RooDataSet data_3("data_3", "dataset with mass (3)", tree_3, RooArgSet(DeltaM,BS));
   RooDataSet data_4("data_4", "dataset with mass (4)", tree_4, RooArgSet(DeltaM,BS));

   // Merge The Datasets
   RooDataSet *mergedData = (RooDataSet*)data_2.Clone(); // Start with data1
   // mergedData->append(data_2); // Add data2
   mergedData->append(data_3); // Add data3
   // mergedData->append(data_4); // Add data4

    // Apply a cut on the merged dataset
    RooDataSet *filteredData = (RooDataSet*)mergedData->reduce("Ds_extraInfo_BkgBDT >= 0.531 && Ds_diff_D0pi >= 0.1 && Ds_diff_D0pi <= 0.55");
   //=========================================================================================================================================================================//
   // C r e a t e   C o m b i n e d   M o d e l
   // ------------------------------------------------------------------------------
   // // Signal:
   // //---------------
   // // First Gamma Function
   // RooRealVar x00_S("x00_S","x00_S", 0.13957, xL, 0.2);
   // RooRealVar a0_S("a0_S","a0_S",  4.4282e-01, 0.0, 1.);
   // RooRealVar b0_S("b0_S","b0_S", 2.6444e+01, 10.0, 50.);    
   // x00_S.setConstant(true);
   // a0_S.setConstant(true);
   // b0_S.setConstant(true);
   // RooFormulaVar x00prime_S("#x00prime_S", "x[0] < x[1] ? x[0] : x[1]", RooArgList(DeltaM, x00_S));     
   // RooFormulaVar gamma0_S("#gamma0_S", "a0_S + 1", RooArgList(a0_S));    
   // RooFormulaVar beta0_for_gamma_S("beta0_for_gamma_S", "1./b0_S", RooArgList(b0_S));    
   // RooGamma GammaModel1_S("GammaModel1_S", "Gamma pdf", DeltaM, gamma0_S, beta0_for_gamma_S, x00prime_S);

   // // Second Gamma Function
   // RooRealVar x01_S("x01_S","x01_S",  0.13957, xL, 0.2);
   // RooRealVar a1_S("a1_S","a1_S", 6.6747e+00, 0.0, 10.);
   // RooRealVar b1_S("b1_S","b1_S", 1.1543e+02, 0.0, 200.);     
   // x01_S.setConstant(true);
   // a1_S.setConstant(true);
   // b1_S.setConstant(true);
   // RooFormulaVar x01prime_S("#x01prime_S", "x[0] < x[1] ? x[0] : x[1]", RooArgList(DeltaM, x01_S));     
   // RooFormulaVar gamma1_S("#gamma1_S", "a1_S + 1", RooArgList(a1_S));    
   // RooFormulaVar beta1_for_gamma_S("beta1_for_gamma_S", "1./b1_S", RooArgList(b1_S));    
   // RooGamma GammaModel2_S("GammaModel2_S", "Gamma pdf", DeltaM, gamma1_S, beta1_for_gamma_S, x01prime_S);

   // // Add the components
   // RooRealVar f0_S("f0_S", "f0", 4.9214e-01, 0, 1);
   // RooRealVar f1_S("f1_S", "f1", 8.7218e-02, 0, 1);
   // f0_S.setConstant(true);
   // f1_S.setConstant(true);
	// RooAddPdf SignalModel("SignalModel","g1+g2",RooArgList(GammaModel1_S,GammaModel2_S), RooArgList(f0_S,f1_S));

   // // Peaking Background:
   // //------------------------
   // RooRealVar sig_mean("sig_mean", "mean of crystal", 1.4541e-01, 0.144, 0.147);
   // RooRealVar sig_sigmaL("sig_sigmaL", "sig_sigmaL", 3.2430e-04, 1e-4, 0.005);
   // RooRealVar sig_sigmaR("sig_sigmaR", "sig_sigmaR", 3.3015e-04, 1e-4, 0.005);
   // RooRealVar sig_alphaL("sig_alphaL", "sig_alphaL", 1.2354e+00, 1e-4, 3.);
   // RooRealVar sig_alphaR("sig_alphaR", "sig_alphaR", 1.1591e+00, 1e-4, 3.);
   // RooRealVar sig_nL("sig_nL", "sig_nL", 5.2534e+00, 1, 6);
   // RooRealVar sig_nR("sig_nR", "sig_nR", 5.3806e+00, 1, 6);
   //  sig_mean.setConstant();
   //  sig_sigmaL.setConstant();
   //  sig_sigmaR.setConstant();
   //  sig_alphaL.setConstant();
   //  sig_alphaR.setConstant();
   //  sig_nL.setConstant();
   //  sig_nR.setConstant();
   // RooCrystalBall PeakingBkgModel("PeakingBkgModel", "sig4", DeltaM, sig_mean,sig_sigmaL,sig_sigmaR,sig_alphaL,sig_nL,sig_alphaR,sig_nR);

   // // Background:
   // //-----------------------
   // // First Gamma Function
   // RooRealVar x00_CBkg("x00_CBkg","x00_CBkg", 0.13957, xL, 0.2);
   // RooRealVar a0_CBkg("a0_CBkg","a0_CBkg", 2.1254e-01, 0.0, 1.);
   // RooRealVar b0_CBkg("b0_CBkg","b0_CBkg", 2.6059e+00, 1.0, 5.);    
   // x00_CBkg.setConstant();
   // a0_CBkg.setConstant();
   // b0_CBkg.setConstant();
   // RooFormulaVar x00prime_CBkg("#x00prime_CBkg", "x[0] < x[1] ? x[0] : x[1]", RooArgList(DeltaM, x00_CBkg));     
   // RooFormulaVar gamma0_CBkg("#gamma0_CBkg", "a0_CBkg + 1", RooArgList(a0_CBkg));    
   // RooFormulaVar beta0_for_gamma_CBkg("beta0_for_gamma_CBkg", "1./b0_CBkg", RooArgList(b0_CBkg));    
   // RooGamma GammaModel1_CBkg("GammaModel1_CBkg", "Gamma pdf", DeltaM, gamma0_CBkg, beta0_for_gamma_CBkg, x00prime_CBkg);

   // // Second Gamma Function
   // RooRealVar x01_CBkg("x01_CBkg","x01_CBkg", 0.13957, xL, 0.2);
   // RooRealVar a1_CBkg("a1_CBkg","a1_CBkg", 4.6803e+00, 1.0, 5.);
   // RooRealVar b1_CBkg("b1_CBkg","b1_CBkg", 6.9240e+00, 2.0, 10.);     
   // x01_CBkg.setConstant();
   // a1_CBkg.setConstant();
   // b1_CBkg.setConstant();
   // RooFormulaVar x01prime_CBkg("#x01prime_S", "x[0] < x[1] ? x[0] : x[1]", RooArgList(DeltaM, x01_CBkg));     
   // RooFormulaVar gamma1_CBkg("#gamma1_CBkg", "a1_CBkg + 1", RooArgList(a1_CBkg));    
   // RooFormulaVar beta1_for_gamma_CBkg("beta1_for_gamma_CBkg", "1./b1_CBkg", RooArgList(b1_CBkg));    
   // RooGamma GammaModel2_CBkg("GammaModel2_CBkg", "Gamma pdf", DeltaM, gamma1_CBkg, beta1_for_gamma_CBkg, x01prime_CBkg);

   // // Third Gamma Function
   // RooRealVar x02_CBkg("x02_CBkg","x02_CBkg", 0.13957, xL, 0.2);
   // RooRealVar a2_CBkg("a2_CBkg","a2_CBkg", 2.0633e+00, 1.0, 5.);
   // RooRealVar b2_CBkg("b2_CBkg","b2_CBkg", 1.2933e+01, 10., 15.);     
   // x02_CBkg.setConstant();
   // a2_CBkg.setConstant();
   // b2_CBkg.setConstant();
   // RooFormulaVar x02prime_CBkg("#x02prime_S", "x[0] < x[1] ? x[0] : x[1]", RooArgList(DeltaM, x02_CBkg));     
   // RooFormulaVar gamma2_CBkg("#gamma2_CBkg", "a2_CBkg + 1", RooArgList(a2_CBkg));    
   // RooFormulaVar beta2_for_gamma_CBkg("beta2_for_gamma_CBkg", "1./b2_CBkg", RooArgList(b2_CBkg));    
   // RooGamma GammaModel3_CBkg("GammaModel3_CBkg", "Gamma pdf", DeltaM, gamma2_CBkg, beta2_for_gamma_CBkg, x02prime_CBkg);

   // // Add the components
   // RooRealVar f0_CBkg("f0_CBkg", "f0", 9.9573e-01, 0, 1);
   // RooRealVar f1_CBkg("f1_CBkg", "f1", 2.7963e-01, 0, 1);
   // RooRealVar f2_CBkg("f2_CBkg", "f2", 4.9076e-01, 0, 1);
   // f0_CBkg.setConstant();
   // f1_CBkg.setConstant();
   // f2_CBkg.setConstant();
   // RooAddPdf CFBkgModel("CFBkgModel","g1+g2",RooArgList(GammaModel1_CBkg,GammaModel2_CBkg,GammaModel3_CBkg), RooArgList(f0_CBkg,f1_CBkg,f2_CBkg));

   // // Fake Signal:
   // //-------------------
   // // First Gamma Function
   // RooRealVar x00_FS("x00_FS","x00_FS", 0.13957, xL, 0.2);
   // RooRealVar a0_FS("a0_FS","a0_FS", 1.8449e+00, 1.0, 4.);
   // RooRealVar b0_FS("b0_FS","b0_FS", 4.9786e+01, 45.0, 55.);    
   // x00_FS.setConstant(true);
   // a0_FS.setConstant(true);
   // b0_FS.setConstant(true);
   // RooFormulaVar x00prime_FS("#x00prime_FS", "x[0] < x[1] ? x[0] : x[1]", RooArgList(DeltaM, x00_FS));     
   // RooFormulaVar gamma0_FS("#gamma0_FS", "a0_FS + 1", RooArgList(a0_FS));    
   // RooFormulaVar beta0_for_gamma_FS("beta0_for_gamma_FS", "1./b0_FS", RooArgList(b0_FS));    
   // RooGamma GammaModel1_FS("GammaModel1_FS", "Gamma pdf", DeltaM, gamma0_FS, beta0_for_gamma_FS, x00prime_FS);

   // // Second Gamma Function
   // RooRealVar x01_FS("x01_FS","x01_FS", 0.13957, xL, 0.2);
   // RooRealVar a1_FS("a1_FS","a1_FS", 2.5070e+00, 2.0, 4.);
   // RooRealVar b1_FS("b1_FS","b1_FS", 3.9739e+02, 350.0, 450.);     
   // x01_FS.setConstant(true);
   // a1_FS.setConstant(true);
   // b1_FS.setConstant(true);
   // RooFormulaVar x01prime_FS("#x01prime_FS", "x[0] < x[1] ? x[0] : x[1]", RooArgList(DeltaM, x01_FS));     
   // RooFormulaVar gamma1_FS("#gamma1_S", "a1_FS + 1", RooArgList(a1_FS));    
   // RooFormulaVar beta1_for_gamma_FS("beta1_for_gamma_FS", "1./b1_FS", RooArgList(b1_FS));    
   // RooGamma GammaModel2_FS("GammaModel2_FS", "Gamma pdf", DeltaM, gamma1_FS, beta1_for_gamma_FS, x01prime_FS);

   // // Third Gamma Function
   // RooRealVar x02_FS("x02_FS","x02_FS", 0.13957, xL, 0.2);
   // RooRealVar a2_FS("a2_FS","a2_FS", 4.6512e-07, 0.0, 0.005);
   // RooRealVar b2_FS("b2_FS","b2_FS", 1.7326e+01, 10.0, 20.);    
   // x02_FS.setConstant(true);
   // a2_FS.setConstant(true);
   // b2_FS.setConstant(true);
   // RooFormulaVar x02prime_FS("#x02prime_FS", "x[0] < x[1] ? x[0] : x[1]", RooArgList(DeltaM, x02_FS));     
   // RooFormulaVar gamma2_FS("#gamma2_FS", "a2_FS + 1", RooArgList(a2_FS));    
   // RooFormulaVar beta2_for_gamma_FS("beta2_for_gamma_FS", "1./b2_FS", RooArgList(b2_FS));    
   // RooGamma GammaModel3_FS("GammaModel3_FS", "Gamma pdf", DeltaM, gamma2_FS, beta2_for_gamma_FS, x02prime_FS);

   // // Add the components
   // RooRealVar f0_FS("f0_FS", "f0", 2.4359e-01, 0, 1);
   // RooRealVar f1_FS("f1_FS", "f1", 2.1751e-02, 0, 1);
   // RooRealVar f2_FS("f2_FS", "f2", 1.3689e-01, 0, 1);
   // f0_FS.setConstant(true);
   // f1_FS.setConstant(true);
   // f2_FS.setConstant(true);
	// RooAddPdf FakeSignalModel("FakeSignalModel","g1+g2+g3",RooArgList(GammaModel1_FS,GammaModel2_FS,GammaModel3_FS), RooArgList(f0_FS,f1_FS,f2_FS));

   // // Other:
   // //------------
   // RooRealVar c0("c0", "coefficient #0", -4.1274e-01, -1, 1);
   // RooRealVar c1("c1", "coefficient #1", -5.0694e-01, -1, 1);
   // RooRealVar c2("c2", "coefficient #2",  3.8160e-01, -1, 1);
   // RooRealVar c3("c3", "coefficient #3",  -3.5603e-02, -1, 1);
   // RooRealVar c4("c4", "coefficient #4", -4.3222e-02, -1, 1);
   // c0.setConstant(true);
   // c1.setConstant(true);
   // c2.setConstant(true);
   // c2.setConstant(true);
   // c3.setConstant(true);
   // c4.setConstant(true);
   // RooChebychev OtherModel("OtherModel", "Other", DeltaM, RooArgList(c0,c1,c2,c3,c4));
   
   //--------------- Combined Model of signal and generic MC ------------------//
   //--------------------------------------------------------------------------//
   // RooRealVar f0("f0", "f0", -100., 10000.);
   // RooRealVar f1("f1", "f1", 1.0e+05, 3.0e+05);
   // RooRealVar f2("f2", "f2", 1.0e+04, 3.0e+05);
   // RooRealVar f3("f3", "f3", 2.0e+04, 9.0e+04);
   // RooRealVar f4("f4", "f4", 1.0e+03, 7.0e+04);
   // RooRealVar f0("f0", "f0", 0, -10000., 10000.);
   RooRealVar f0("f0", "f0", 0, -50000., 50000.);
   RooRealVar f1("f1", "f1", 2.0573e+05, 1.0e+05, 3.0e+05);
   RooRealVar f2("f2", "f2", 1.7827e+05, 1.0e+05, 3.0e+05);
   // RooRealVar f2("f2", "f2", 1.7827e+05, 1.0e+02, 3.0e+05);
   RooRealVar f3("f3", "f3", 7.1229e+04, 3.0e+04, 12.0e+04);
   // RooRealVar f3("f3", "f3", 7.1229e+04, 3.0e+04, 9.0e+05);
   RooRealVar f4("f4", "f4", 5.1740e+03, 2.0e+03, 7.0e+03);
   // RooRealVar f4("f4", "f4", 5.1740e+03, 2.0e+00, 7.0e+05);
   // f0.setConstant(true);
   // f1.setConstant(true);
   // f2.setConstant(true);
   // f3.setConstant(true);
   // f4.setConstant(true);
   // RooAddPdf model("model", "s+pbkg+cbkg+fs", RooArgList(SignalModel,PeakingBkgModel,CFBkgModel,FakeSignalModel,OtherModel), RooArgList(f0,f1,f2,f3,f4));
   // RooAddPdf model("model", "s+pbkg+cbkg+fs", RooArgList(*SignalModel,*DstarPModel,*D0BkgModel), RooArgList(f0,f1,f3));
   // RooAddPdf model("model", "s+pbkg+cbkg+fs", RooArgList(*SignalModel,*Dstar0BkgModel), RooArgList(f0,f2));
   // RooAddPdf model("model", "s+pbkg+cbkg+fs", RooArgList(*SignalModel,*D0BkgModel), RooArgList(f0,f3));
   RooAddPdf model("model", "s+pbkg+cbkg+fs", RooArgList(*SignalModel,*Dstar0BkgModel,*D0BkgModel), RooArgList(f0,f2,f3));
   // RooAddPdf model("model", "s+pbkg+cbkg+fs", RooArgList(*SignalModel,*DstarPModel,*OtherModel), RooArgList(f0,f1,f4));
   // RooAddPdf model("model", "s+pbkg+Dstar0+D0+fD0", RooArgList(*SignalModel,*DstarPModel,*Dstar0BkgModel,*D0BkgModel,*OtherModel), RooArgList(f0,f1,f2,f3,f4));
   //=========================================================================================================================================================================//
   // S e t   t h e   C o n s t a n t   f o r   t h e    V a r i a b l e s
   //--------------------------------------------------------------------------
   // The code below fixes the value for a certain value.
   // f0.setVal();
   // f1.setVal();
   // f2.setVal();

   // The code below removes the range and fixes the value.
   // f0.setConstant(true);
   // f1.setConstant(true);
   // f2.setConstant(true);

   // DeltaM.setVal(0.0065);
   // DeltaM.setConstant(true);
   //=========================================================================================================================================================================//
   // F i t
   //-------------
   // Perform extended ML fit of data:
   std::unique_ptr<RooFitResult> r{model.fitTo(*filteredData, Save(), PrintLevel(-1))};
   // If the fit is too broad and does not seem to fit a peak use the code below. Use it
   // once to determine where the peak should be and then adjust the mean above.
   // model.fitTo(data, Minos(kTRUE), PrintLevel(-1), Range(2,2.1));
   //=========================================================================================================================================================================//
   // P l o t 
   //---------
   // // Create binning object with range (0.1,0.55)
   // RooBinning tbins(xL, xR);
 
   // // Add 60 bins with uniform spacing in range (0.1,0.16)
   // tbins.addUniform(50, xL, 0.16);
 
   // // Add 15 bins with uniform spacing in range (0.15,0.55)
   // tbins.addUniform(20, 0.16, xR);

   RooPlot* frame = DeltaM.frame();
   *filteredData->plotOn(frame, Binning(bin));

   model.plotOn(frame, Components(*SignalModel),     LineStyle(kDashed), LineColor(kAzure-2),    RooFit::Name("Signal"));
   // model.plotOn(frame, Components(*DstarPModel),     LineStyle(kDashed), LineColor(kGreen+1),    RooFit::Name("DstarP"));
   model.plotOn(frame, Components(*Dstar0BkgModel),  LineStyle(kDashed), LineColor(kOrange+8),   RooFit::Name("Dstar0"));
   model.plotOn(frame, Components(*D0BkgModel),      LineStyle(kDashed), LineColor(kViolet-3),   RooFit::Name("D0"));
   // model.plotOn(frame, Components(*OtherModel),      LineStyle(kDashed), LineColor(kOrange-7),   RooFit::Name("Other"));

   // model.plotOn(frame, Components(*SignalModel),     LineStyle(kDashed), LineColor(38),   RooFit::Name("Signal"));
   // model.plotOn(frame, Components(*PeakingBkgModel), LineStyle(kDashed), LineColor(28),   RooFit::Name("PeakingBackground"));
   // model.plotOn(frame, Components(*Background),      LineStyle(kDashed), LineColor(kRed), RooFit::Name("Background"));
   // model.plotOn(frame, Components(*FakeSignal),     LineStyle(kDashed), LineColor(30),   RooFit::Name("FSignal"));

   model.plotOn(frame, LineColor(41), RooFit::Name("model"));
   // *PeakingBkgModel->plotOn(frame, LineColor(38), RooFit::Name("model"));
   //=========================================================================================================================================================================//
   // C a l c u l a t e   c h i ^ 2
   // ------------------------------
   // Show the chi^2 of the curve w.r.t. the histogram
   // If multiple curves or datasets live in the frame you can specify
   // the name of the relevant curve and/or dataset in chiSquare()
   Int_t npar = model.getParameters(*filteredData)->selectByAttrib("Constant",kFALSE)->getSize(); //select floating parameters and count their number

   cout << "NDF = " << npar << endl;
   cout << "chi^2/NDF = " << frame->chiSquare(npar) << endl;

   Double_t chi2ndf = frame->chiSquare(npar);
   //=========================================================================================================================================================================//
   // P l o t    L a b e l s
   // ---------------------------------------------------------------------------
   // Add text to frame
   TLatex *latex = new TLatex();
   TString lum ("");
   lum.Form("#splitline{Generic c#bar{c} Events}{#scale[0.5]{#int}#it{L} dt=1.44 ab^{-1}}");
   // lum.Form("#splitline{Generic c#bar{c} Events}{#scale[0.5]{#int}#it{L} dt=200 fb^{-1}}");
   latex->SetNDC();
   latex->SetTextSize(0.03); 
   
   auto PerBin = ((xR-xL)/(bin))*1000;
   // TString title ("");
   TString y_axis ("");
   // TString x_axis ("");

   // title.Form("Generic d#bar{d} Events");
   y_axis.Form("Entries/(%.2f MeV/c^{2})", PerBin);
   // x_axis.Form("#Delta m  [GeV/c^{2}]");

   frame->SetTitle("");
   frame->GetYaxis()->SetTitle(y_axis);
   frame->GetXaxis()->SetTitle("");
   // frame->GetXaxis()->CenterTitle(true);
   // pad1->SetLogx();
   // Set log scale for Y-axis
   pad1->SetLogy();

   // Ensure Y-range is properly set
   frame->GetYaxis()->SetRangeUser(1, 10e+05); // Log scale cannot have 0
   frame->Draw();

   // The line below prints the luminosity onto the screen.
   // latex->DrawLatex(0.6,0.2, lum);
   latex->DrawLatex(0.2,0.89, lum);
   //=========================================================================================================================================================================//
   // P a r a m e t e r   B o x
   // ---------------------------------------------------------------------------
   auto xIF1 = pad1 -> GetUxmin() + pad1 -> GetLeftMargin();
   auto xIF2 = pad1 -> GetUxmax() - pad1 -> GetRightMargin();
   auto yIF1 = pad1 -> GetUymin() + pad1 -> GetBottomMargin();
   auto yIF2 = pad1 -> GetUymax() - pad1 -> GetTopMargin();
   auto dx = xIF2 - xIF1;
   auto dy = yIF2 - yIF1;
   auto x1 = xIF1 + 0.35*dx;
   // auto x1 = xIF1 + 0.55*dx;
   auto x2 = 0.92 ;
   auto y1 = yIF1 + 0.7*dy;
   auto y2 = 0.93;
   auto legend = new TLegend(x1, y1, x2, y2);

   TString chi2("");
   TString N_sig("");
   TString N_DstarP("");
   TString N_Dstar0("");
   TString N_D0("");
   TString N_O("");

   chi2.Form("#chi^{2}/ndf = %.2f", chi2ndf);
   N_sig.Form("N_{sig} = %.2f #pm %.2f", f0.getValV(), f0.getError());
   N_DstarP.Form("N_{D^{*+}} = %.2f #pm %.2f", f1.getValV(), f1.getError());
   N_Dstar0.Form("N_{D^{*0}} = %.2f #pm %.2f", f2.getValV(), f2.getError());
   N_D0.Form("N_{D^{0}} = %.2f #pm %.2f", f3.getValV(), f3.getError());
   N_O.Form("N_{Other} = %.2f #pm %.2f", f4.getValV(), f4.getError());

   // Legend
   legend->AddEntry(frame->FindObject("data"),"data","pe");
   legend->AddEntry((TObject *)0, chi2, "");
   legend->AddEntry("Signal", "Signal Fit", "pl" );
   legend->AddEntry((TObject *)0, N_sig, "");
   // legend->AddEntry("DstarP", "D^{*+} #rightarrow D^{0} #pi^{+}", "pl" );
   // legend->AddEntry((TObject *)0, N_DstarP, "");
   legend->AddEntry("Dstar0", "D^{*0} #rightarrow D^{0} #gamma, D^{0} #pi^{0}", "pl" );
   legend->AddEntry((TObject *)0, N_Dstar0, "");
   legend->AddEntry("D0", "D^{0}", "pl" );
   legend->AddEntry((TObject *)0, N_D0, "");
   // legend->AddEntry("Other", "Other", "pl" );
   // legend->AddEntry((TObject *)0, N_O, "");
   legend->AddEntry("model", "Total Fit", "pl" );
   // // Labels
   // legend->AddEntry(frame->FindObject("data"),"data","pe");
   // legend->AddEntry("Signal", "Signal Fit", "pl" );
   // legend->AddEntry("PeakingBackground", "D^{*+} #rightarrow [D^{0} #rightarrow K^{-} #pi^{+}] #pi^{+}", "pl" );
   // legend->AddEntry("Background", "comb.+failed", "pl" );
   // legend->AddEntry("FSignal", "D^{*0} Background", "pl" );
   // legend->AddEntry("model", "Total Fit", "pl" );

   legend -> SetBorderSize(0);
   legend -> SetTextFont(132);
   legend -> SetTextSize(0.03);
   legend -> SetNColumns(2);
   // legend -> SetNColumns(1);
   legend -> SetMargin(0.1);
   legend->Draw();
   //=========================================================================================================================================================================//
   // S h o w   P a r a m e t e r/ F i t    R e s u l t s
   // -------------------------------------------------------
   // When I use rooworkspace this first part will make sure that the parameters of the 
   // model will stay fixed.
   // N.setConstant(true);
   // N.removeError();
   // b.setConstant(true);
   // b.removeError();
   // P.setConstant(true);
   // P.removeError();

   // Verbose printing: Basic info, values of constant parameters, initial and
   // final values of floating parameters, global correlations
   r->Print("v");

   // Access basic information
   cout << "EDM = " << r->edm() << endl;
   cout << "-log(L) at minimum = " << r->minNll() << endl;

   // Extract covariance and correlation matrix as TMatrixDSym
   const TMatrixDSym &cor = r->correlationMatrix();
   const TMatrixDSym &cov = r->covarianceMatrix();
 
   // Print correlation, covariance matrix
   cout << "Correlation Matrix" << endl;
   cor.Print();
   cout << "Covariance Matrix" << endl;
   cov.Print();
   //=========================================================================================================================================================================//
   // S h o w   r e s i d u a l   d i s t s
   // -------------------------------------------------------
   pad2->cd();
   // Construct a histogram with the residuals of the data w.r.t. the curve
   RooHist *hresid = frame->residHist();
   for(int iPoint = 0; iPoint < hresid->GetN(); ++iPoint) {
      hresid->SetPointEYlow(iPoint, 0.0);
      hresid->SetPointEYhigh(iPoint, 0.0);
   }
   hresid->SetFillColor(38);
   // hresid->SetLineWidth(-802);
   // hresid->SetFillStyle(3002);
   // hresid->SetFillColor(2);

   // Create a new frame to draw the residual distribution and add the distribution to the frame
   RooPlot *frame1 = DeltaM.frame(Title("Residual Distribution"));
   frame1->addPlotable(hresid, "B");
   frame1->Draw();
   
   // Plot Titles
   //---------------
   frame1->SetTitle("");

   // Y-axis
   frame1->SetYTitle("Residual");
   frame1->GetYaxis()->CenterTitle(true);
   frame1->GetYaxis()->SetTitleSize(0.10);
   frame1->GetYaxis()->SetLabelSize(0.10);

   // X-axis
   TString x_axis ("");
   x_axis.Form("#Delta m  [GeV/c^{2}]");
   frame1->SetXTitle(x_axis);
   frame1->GetXaxis()->CenterTitle(true);
   frame1->GetXaxis()->SetTitleSize(0.13);
   frame1->GetXaxis()->SetLabelSize(0.10);
   // pad2->SetLogx();
   // pad2->SetLogy();

   frame1->SetTitleOffset(0.5, "Y");

   // Draw Horizontal Line On Residual Plot
   //----------------------------------------
   // double xmin1 = xIF1; 
   // double xmax1 = 1.0;
   // TLine *line11 = new TLine(xIF1,0.0,xIF2,0.0);
   // line11->SetLineColor(kRed); line11->SetLineWidth(3);
   // line11->Draw("SAME");

   c->cd();
   //=========================================================================================================================================================================//
   // S a v e   t h e   P l o t 
   //-------------------------------
   c->SaveAs("/home/belle2/amubarak/Ds2D0enue_Analysis/05-ROOT/Roofit_Suggestion/Fit_Image/rs06_Combined_Multiple.png");
   //=========================================================================================================================================================================//
   // Uncertainty Calculations
   //---------------------------------------------
   Float_t LumS = 400e15;
   Float_t Lum = 1443.999e15;
   Float_t Cross = 1.329e-9;
   Float_t cDs = 0.10;
   Float_t D0 = 0.03947;
   Float_t Efficiency = 0.08016;

   Float_t Central = (f0.getValV()*(LumS/Lum))/(LumS*Cross*2*cDs*D0*Efficiency);
   Float_t UpperLimit = (f0.getError()*(LumS/Lum))/(LumS*Cross*2*cDs*D0*Efficiency);

   cout << endl << "Central= " << Central << endl;
   cout << "Upper Limit 68% Confidence= " << UpperLimit << endl;
   cout << "Upper Limit 95% Confidence= " << 2*UpperLimit << endl;

   cout << endl << "Total= " << (f1.getValV() + f2.getValV() + f3.getValV() + f4.getValV()) << endl << endl;
   //=========================================================================================================================================================================//
   // Final Fit Status
   //---------------------------
   int fitStatus = r->status();  // Get the fit status
   int covQual = r->covQual();   // Get covariance quality

   std::cout << "Fit Status: " << fitStatus << std::endl;
   std::cout << "Covariance Matrix Quality: " << covQual << std::endl << endl;

}