#include "RooRealVar.h"
#include "RooDataSet.h"
#include "RooGaussian.h"
#include "RooChebychev.h"
#include "RooAddPdf.h"
#include "RooWorkspace.h"
#include "RooPlot.h"
#include "TCanvas.h"
#include "TAxis.h"
#include "TFile.h"
#include "TH1.h"
using namespace RooFit;
 
void rf03_Combined()
{
   // S e t u p   t h e   F r a m e   f o r   t h e   P l o t
   //------------------------------------------------------------
   TCanvas *c = new TCanvas("fit", "fit", 650, 700);
   TPad *pad1 = new TPad("pad1","pad1",0,0.25,1,1);
   TPad *pad2 = new TPad("pad2","pad2",0,0,1,0.25);
   pad1->SetTopMargin(0.05);
   pad1->SetBottomMargin(0.05);
   pad1->SetLeftMargin(0.15);
   pad1->SetRightMargin(0.05);
   pad2->SetLeftMargin(0.15);
   pad2->SetRightMargin(0.05);
   pad2->SetTopMargin(0.01);
   pad2->SetBottomMargin(0.4);
   // pad2->SetBorderMode(0);
   pad1->Draw();
   pad2->Draw();
   pad1->cd();
   gStyle->SetOptStat(0);
   //=========================================================================================================================================================================//
   // R e a d   w o r k s p a c e   f r o m   f i l e
   // -----------------------------------------------
   // Open input file with workspace (generated by rf503_wspacewrite)
   // TFile *f_S = new TFile("Ds2D0enue_Analysis/05-ROOT/Fit_Parameter/rf00_SignalPara.root");
   TFile *f_PBkg = new TFile("Ds2D0enue_Analysis/05-ROOT/Fit_Parameter/rf01_PeakingBkgPara.root");
   // TFile *f_CFBkg = new TFile("Ds2D0enue_Analysis/05-ROOT/Fit_Parameter/rf02_CombinatorialBkgPara.root");

 
   // // R e t r i e v e   p d f   f r o m   w o r k s p a c e
   // // -----------------------------------------------------------------
   // // Signal
   // RooWorkspace *w_S = (RooWorkspace *)f_S->Get("w_S");
   // RooRealVar *M_S = w_S->var("Ds_diff_D0pi");
   // RooAbsPdf *SignalModel = w_S->pdf("SignalModel");
   // w_S->loadSnapshot("reference_fit_Signal");

   // Peaking Background
   RooWorkspace *w_PBkg = (RooWorkspace *)f_PBkg->Get("w_PBkg");
   RooRealVar *M_PBkg = w_PBkg->var("Ds_diff_D0pi");
   RooAbsPdf *PeakingBkgModel = w_PBkg->pdf("PeakingBkgModel");

   // Combinatorial + Failed Background
   // RooWorkspace *w_CFBkg = (RooWorkspace *)f_CFBkg->Get("w_CBkg");
   // RooRealVar *M_CFBkg = w_CFBkg->var("Ds_diff_D0pi");
   // RooAbsPdf *Background = w_CFBkg->pdf("CFBkgModel");
   //=========================================================================================================================================================================//
   // I n i t i a l i z a t i o n:
   // --------------------------------------------------------------
   // The lines below initializes all my values
   int bin = 50;
   double xL = 0.1;
   double xR = 1;
   //=========================================================================================================================================================================//
   // I m p o r t s   D a t a   f r o m   t r e e   b r a n c h:
   // --------------------------------------------------------------
   TFile *file = new TFile("C03-Grid/Completed/Ds2D0e-Generic_Ds_100124_0_ccbar.root");
   TTree *tree = (TTree*)file->Get("Dstree");
   //=========================================================================================================================================================================//
   // D a t a:
   // --------------------------------------------------------------
   RooRealVar DeltaM("Ds_diff_D0pi", "Mass Difference", xL, xR);
   RooRealVar Veto("Ds_gammaveto_M_Correction","Veto",0.1,100);
   RooRealVar BCS("Ds_chiProb_rank","BCS",-1,1.25);
   // RooRealVar Category("Ds_Ds_starminusDs_M_Correction","Category",0.12,0.165);

   // RooDataSet data("data", "dataset with mass", tree, RooArgSet(M,x,y));
   RooDataSet data("data", "dataset with mass", tree, RooArgSet(DeltaM,Veto,BCS));
   //=========================================================================================================================================================================//
   // C r e a t e   C o m b i n e d   M o d e l
   // ------------------------------------------------------------------------------
   // --- Build Background Model --- 
   //--------------------------------------------------------------------------//
   // Generic PDF
   RooRealVar B0_CBkg("B0_CBkg", "B0_CBkg", -40., 20.);
   RooRealVar P0_CBkg("P0_CBkg", "P0_CBkg", 0., 5.);
   RooGenericPdf Generic0_CBkg("Generic0_CBkg","Generic PDF","(Ds_diff_D0pi - 0.13953 > 0 ? ( ((Ds_diff_D0pi-0.13953)^P0_CBkg)*exp( B0_CBkg*(Ds_diff_D0pi-0.13953))) : 0.0)", RooArgSet( DeltaM, B0_CBkg, P0_CBkg));

   // Generic PDF
   RooRealVar B1_CBkg("B1_CBkg", "B1_CBkg", -40., 20.);
   RooRealVar P1_CBkg("P1_CBkg", "P1_CBkg", 0., 5.);
   RooGenericPdf Generic1_CBkg("Generic1_CBkg","Generic PDF","(Ds_diff_D0pi - 0.13953 > 0 ? ( ((Ds_diff_D0pi-0.13953)^P1_CBkg)*exp( B1_CBkg*(Ds_diff_D0pi-0.13953))) : 0.0)", RooArgSet( DeltaM, B1_CBkg, P1_CBkg));

   // Combined Background
   RooRealVar f0_CBkg("f0_CBkg", "f0", 1);
   RooRealVar f1_CBkg("f1_CBkg", "f1", 1);
   RooAddPdf CFBkgModel("CFBkgModel", "b+c", RooArgList(Generic0_CBkg,Generic1_CBkg), RooArgList(f0_CBkg,f1_CBkg));
   
   //------- Combined Model of signal and generic MC ----------//
   //--------------------------------------------------------------------------//
   // RooRealVar f0("f0", "f0", 0., 10000.);
   RooRealVar f1("f1", "f1", 25079, 10000., 50000.);
   RooRealVar f2("f2", "f2", 1);
   RooAddPdf model("model", "s+pbkg+cbkg", RooArgList(*PeakingBkgModel,CFBkgModel), RooArgList(f1,f2));
   // RooAddPdf model("model", "s+pbkg+cbkg", RooArgList(*SignalModel,*PeakingBkgModel,*Background), RooArgList(f0,f1,f2));

   w_PBkg->loadSnapshot("reference_fit_PeakingBkg");
   // w_CFBkg->loadSnapshot("reference_fit_Combinatorial_Bkg");
   //=========================================================================================================================================================================//
   // S e t   t h e   C o n s t a n t   f o r   t h e    V a r i a b l e s
   //--------------------------------------------------------------------------
   // The code below fixes the value for a certain value.
   // DeltaM.setVal(0.55);
   // f1_CBkg.setVal(1);
   // cs2.setVal(6.6959e+04);
   // se0.setVal(4.3809e-13);
   // se1.setVal(2.1380e-12);
   // se2.setVal(3.7987e-01);
   // se3.setVal(5.2111e-02);
   // x0.setVal(7.1101e-02);

   // // The code below removes the range and fixes the value.
   // DeltaM.setConstant(true);
   // f0_CBkg.setConstant(true);
   // cs1.setConstant(true);
   // cs2.setConstant(true);
   // se0.setConstant(true);
   // se1.setConstant(true);
   // se2.setConstant(true);
   // se3.setConstant(true);
   // x0.setConstant(true);
   // sigmean1.removeError();
   // sigmean2.removeError();
   // sigwidth1.removeError();
   // sigwidth2.removeError();
   //=========================================================================================================================================================================//
   // F i t
   //-------------
   // Perform extended ML fit of data:
   // std::unique_ptr<RooFitResult> r{model.fitTo(data, Save(), PrintLevel(-1))};
   // If the fit is too broad and does not seem to fit a peak use the code below. Use it
   // once to determine where the peak should be and then adjust the mean above.
   // model.fitTo(data, Minos(kTRUE), PrintLevel(-1), Range(2,2.1));
   //=========================================================================================================================================================================//
   // P l o t 
   //---------
   RooPlot* frame = DeltaM.frame();
   data.plotOn(frame, Binning(bin));
   // model.plotOn(frame, Components(*Background),      LineStyle(kDashed), LineColor(kRed), RooFit::Name("Background"));
   // model.plotOn(frame, Components(*PeakingBkgModel), LineStyle(kDashed), LineColor(46),   RooFit::Name("PeakingBackground"));
   // model.plotOn(frame, Components(*SignalModel),     LineStyle(kDashed), LineColor(38),   RooFit::Name("Signal"));
   model.plotOn(frame, LineColor(38), RooFit::Name("model"));
   // model.plotOn(frame);
   // //=========================================================================================================================================================================//
   // // C a l c u l a t e   c h i ^ 2
   // // ------------------------------
   // // Show the chi^2 of the curve w.r.t. the histogram
   // // If multiple curves or datasets live in the frame you can specify
   // // the name of the relevant curve and/or dataset in chiSquare()
   // Int_t npar = model.getParameters(data)->selectByAttrib("Constant",kFALSE)->getSize(); //select floating parameters and count their number

   // cout << "NDF = " << npar << endl;
   // cout << "chi^2/NDF = " << frame->chiSquare(npar) << endl;

   // Double_t chi2ndf = frame->chiSquare(npar);
   //=========================================================================================================================================================================//
   // P l o t    L a b e l s
   // ---------------------------------------------------------------------------
   // Add text to frame
   TLatex *latex = new TLatex();
   TString lum ("");
   lum.Form("#splitline{Generic c#bar{c} Events}{#scale[0.5]{#int}#it{L} dt=100 fb^{-1}}");
   latex->SetNDC();
   latex->SetTextSize(0.03); 
   
   auto PerBin = ((xR-xL)/(bin))*1000;
   // TString title ("");
   TString y_axis ("");
   // TString x_axis ("");

   // title.Form("Generic d#bar{d} Events");
   y_axis.Form("Entries/(%.2f MeV/c^{2})", PerBin);
   // x_axis.Form("#Delta m  [GeV/c^{2}]");

   frame->SetTitle("");
   frame->GetYaxis()->SetTitle(y_axis);
   frame->GetYaxis()->SetRangeUser(0,65000);
   frame->GetXaxis()->SetTitle("");
   // frame->GetXaxis()->CenterTitle(true);
   frame->Draw();

   // The line below prints the luminosity onto the screen.
   // latex->DrawLatex(0.6,0.2, lum);
   latex->DrawLatex(0.18,0.89, lum);
   //=========================================================================================================================================================================//
   // P a r a m e t e r   B o x
   // ---------------------------------------------------------------------------
   auto xIF1 = pad1 -> GetUxmin() + pad1 -> GetLeftMargin();
   auto xIF2 = pad1 -> GetUxmax() - pad1 -> GetRightMargin();
   auto yIF1 = pad1 -> GetUymin() + pad1 -> GetBottomMargin();
   auto yIF2 = pad1 -> GetUymax() - pad1 -> GetTopMargin();
   auto dx = xIF2 - xIF1;
   auto dy = yIF2 - yIF1;
   auto x1 = xIF1 + 0.4*dx;
   auto x2 = xIF2;
   auto y1 = yIF1 + 0.75*dy;
   auto y2 = 0.93;
   auto legend = new TLegend(x1, y1, x2, y2);

   TString chi2("");
   TString N_sig("");
   TString N_PBkg("");
   TString N_CBkg("");

   // chi2.Form("#chi^{2}/ndf = %.2f", chi2ndf);
   // N_sig.Form("N_{sig} = %.2f #pm %.2f", f0.getValV(), f0.getError());
   // N_PBkg.Form("N_{PBkg} = %.2f #pm %.2f", f1.getValV(), f1.getError());
   // N_CBkg.Form("N_{CBkg} = %.2f #pm %.2f", f2.getValV(), f2.getError());

   // legend->AddEntry(frame->FindObject("data"),"data","pe");
   // legend->AddEntry((TObject *)0, chi2, "");
   // legend->AddEntry("Signal", "Signal Fit", "pl" );
   // legend->AddEntry((TObject *)0, N_sig, "");
   // legend->AddEntry("PeakingBackground", "D^{*+} #rightarrow [D^{0} #rightarrow K^{-} #pi^{+}] #pi^{+}", "pl" );
   // legend->AddEntry((TObject *)0, N_PBkg, "");
   // legend->AddEntry("Background", "Background Fit", "pl" );
   // legend->AddEntry((TObject *)0, N_CBkg, "");
   // legend->AddEntry("model", "Total Fit", "pl" );

   // legend -> SetBorderSize(0);
   // legend -> SetTextFont(132);
   // legend -> SetTextSize(0.03);
   // legend -> SetNColumns(2);
   // legend -> SetMargin(0.1);
   // legend->Draw();
   //=========================================================================================================================================================================//
   // S h o w   P a r a m e t e r/ F i t    R e s u l t s
   // -------------------------------------------------------
   // When I use rooworkspace this first part will make sure that the parameters of the 
   // model will stay fixed.
   // N.setConstant(true);
   // N.removeError();
   // b.setConstant(true);
   // b.removeError();
   // P.setConstant(true);
   // P.removeError();

   // // Verbose printing: Basic info, values of constant parameters, initial and
   // // final values of floating parameters, global correlations
   // r->Print("v");

   // // Access basic information
   // cout << "EDM = " << r->edm() << endl;
   // cout << "-log(L) at minimum = " << r->minNll() << endl;

   // // Extract covariance and correlation matrix as TMatrixDSym
   // const TMatrixDSym &cor = r->correlationMatrix();
   // const TMatrixDSym &cov = r->covarianceMatrix();
 
   // // Print correlation, covariance matrix
   // cout << "correlation matrix" << endl;
   // cor.Print();
   // cout << "covariance matrix" << endl;
   // cov.Print();
   //=========================================================================================================================================================================//
   // S h o w   r e s i d u a l   d i s t s
   // -------------------------------------------------------
   pad2->cd();
   // Construct a histogram with the residuals of the data w.r.t. the curve
   RooHist *hresid = frame->residHist();
   for(int iPoint = 0; iPoint < hresid->GetN(); ++iPoint) {
      hresid->SetPointEYlow(iPoint, 0.0);
      hresid->SetPointEYhigh(iPoint, 0.0);
   }
   hresid->SetFillColor(38);
   // hresid->SetLineWidth(-802);
   // hresid->SetFillStyle(3002);
   // hresid->SetFillColor(2);

   // Create a new frame to draw the residual distribution and add the distribution to the frame
   RooPlot *frame1 = DeltaM.frame(Title("Residual Distribution"));
   frame1->addPlotable(hresid, "B");
   frame1->Draw();
   
   // Plot Titles
   //---------------
   frame1->SetTitle("");

   // Y-axis
   frame1->SetYTitle("Residual");
   frame1->GetYaxis()->CenterTitle(true);
   frame1->GetYaxis()->SetTitleSize(0.10);
   frame1->GetYaxis()->SetLabelSize(0.10);

   // X-axis
   TString x_axis ("");
   x_axis.Form("#Delta m  [GeV/c^{2}]");
   frame1->SetXTitle(x_axis);
   frame1->GetXaxis()->CenterTitle(true);
   frame1->GetXaxis()->SetTitleSize(0.13);
   frame1->GetXaxis()->SetLabelSize(0.10);

   frame1->SetTitleOffset(0.5, "Y");

   // Draw Horizontal Line On Residual Plot
   //----------------------------------------
   // double xmin1 = xIF1; 
   // double xmax1 = 1.0;
   // TLine *line11 = new TLine(xIF1,0.0,xIF2,0.0);
   // line11->SetLineColor(kRed); line11->SetLineWidth(3);
   // line11->Draw("SAME");

   c->cd();
   //=========================================================================================================================================================================//
   // S a v e   t h e   P l o t 
   //-------------------------------
   c->SaveAs("Ds2D0enue_Analysis/09-Images/rf03_DeltaM_Combined.png");
   //=========================================================================================================================================================================//
}