#include "RooRealVar.h"
#include "RooDataSet.h"
#include "RooGaussian.h"
#include "RooChebychev.h"
#include "RooAddPdf.h"
#include "RooWorkspace.h"
#include "RooPlot.h"
#include "TCanvas.h"
#include "TAxis.h"
#include "TFile.h"
#include "TH1.h"
using namespace RooFit;
 
void rs05_Combined()
{
   // S e t u p   t h e   F r a m e   f o r   t h e   P l o t
   //------------------------------------------------------------
   TCanvas *c = new TCanvas("fit", "fit", 650, 700);
   TPad *pad1 = new TPad("pad1","pad1",0,0.25,1,1);
   TPad *pad2 = new TPad("pad2","pad2",0,0,1,0.25);
   pad1->SetTopMargin(0.05);
   pad1->SetBottomMargin(0.05);
   pad1->SetLeftMargin(0.15);
   pad1->SetRightMargin(0.05);
   pad2->SetLeftMargin(0.15);
   pad2->SetRightMargin(0.05);
   pad2->SetTopMargin(0.01);
   pad2->SetBottomMargin(0.4);
   // pad2->SetBorderMode(0);
   pad1->Draw();
   pad2->Draw();
   pad1->cd();
   gStyle->SetOptStat(0);
   //=========================================================================================================================================================================//
   // R e a d   w o r k s p a c e   f r o m   f i l e
   // -----------------------------------------------
   // Open input file with workspace (generated by rf503_wspacewrite)
   TFile *f_S = new TFile("/home/belle2/amubarak/Ds2D0enue_Analysis/10-Save/Roofit_Suggestion_Likehood_Window/Fit_Parameter/rs00_SignalPara.root");
   TFile *f_DstarP = new TFile("/home/belle2/amubarak/Ds2D0enue_Analysis/10-Save/Roofit_Suggestion_Likehood_Window/Fit_Parameter/rs01_DstarP.root");
   TFile *f_Dstar0 = new TFile("/home/belle2/amubarak/Ds2D0enue_Analysis/10-Save/Roofit_Suggestion_Likehood_Window/Fit_Parameter/rs02_Dstar0.root");
   TFile *f_D0 = new TFile("/home/belle2/amubarak/Ds2D0enue_Analysis/10-Save/Roofit_Suggestion_Likehood_Window/Fit_Parameter/rs03_D0.root");
   TFile *f_O = new TFile("/home/belle2/amubarak/Ds2D0enue_Analysis/10-Save/Roofit_Suggestion_Likehood_Window/Fit_Parameter/rs04_OtherPara.root");
 
   // R e t r i e v e   p d f   f r o m   w o r k s p a c e
   // -----------------------------------------------------------------
   // Signal
   RooWorkspace *w_S = (RooWorkspace *)f_S->Get("w_S");
   // RooRealVar *M_S = w_S->var("Ds_diff_D0pi");
   RooAbsPdf *SignalModel = w_S->pdf("SignalModel");

   // Peaking Background
   RooWorkspace *w_DstarP = (RooWorkspace *)f_DstarP->Get("w_Dstarp");
   // RooRealVar *M_PBkg = w_PBkg->var("Ds_diff_D0pi");
   RooAbsPdf *DstarPModel = w_DstarP->pdf("DstarPModel");

   // Combinatorial + Failed Background
   RooWorkspace *w_Dstar0 = (RooWorkspace *)f_Dstar0->Get("w_Dstar0");
   // RooRealVar *M_CFBkg = w_CFBkg->var("Ds_diff_D0pi");
   RooAbsPdf *Dstar0BkgModel = w_Dstar0->pdf("Dstar0BkgModel");

   // Fake Signal
   RooWorkspace *w_D0 = (RooWorkspace *)f_D0->Get("w_D0");
   // RooRealVar *M_CFBkg = w_CFBkg->var("Ds_diff_D0pi");
   RooAbsPdf *D0BkgModel = w_D0->pdf("D0BkgModel");

   // Other
   RooWorkspace *w_O = (RooWorkspace *)f_O->Get("w_O");
   // RooRealVar *M_OBkg = w_CFBkg->var("Ds_diff_D0pi");
   RooAbsPdf *OtherModel = w_O->pdf("OtherModel");

   w_S->loadSnapshot("reference_fit_Signal");
   w_DstarP->loadSnapshot("reference_fit_Dstarp_Bkg");
   w_Dstar0->loadSnapshot("reference_fit_Dstar0_Bkg");
   w_D0->loadSnapshot("reference_fit_D0");
   w_O->loadSnapshot("reference_fit_Other");
   //=========================================================================================================================================================================//
   // I n i t i a l i z a t i o n:
   // --------------------------------------------------------------
   // The lines below initializes all my values
   int bin = 50;
   double xL = 0.16;
   double xR = 0.45;
   //=========================================================================================================================================================================//
   // I m p o r t s   D a t a   f r o m   t r e e   b r a n c h:
   // --------------------------------------------------------------
   // Total Viewing
   // TFile *file = new TFile("/group/belle2/users2022/amubarak/02-Grid/Completed_TopoAna/Ds2D0e-Generic_Ds_021325_2_ccbar.root");
   // TTree *tree = (TTree*)file->Get("Dstree");
   // Individual Viewing
   TFile *file = new TFile("/home/belle2/amubarak/C03-Grid/TopoAna.root");
   TTree *tree_1 = (TTree*)file->Get("Dstarplus");
   TTree *tree_2 = (TTree*)file->Get("Dstar0");
   TTree *tree_3 = (TTree*)file->Get("D0");
   TTree *tree_4 = (TTree*)file->Get("FakeD0");
   //=========================================================================================================================================================================//
   // D a t a:
   // --------------------------------------------------------------
   RooRealVar DeltaM("Ds_diff_D0pi", "Mass Difference", xL, xR);
   RooRealVar BS("Ds_extraInfo_BkgBDT", "Background Suppression", 0.0, 1.0);

   RooDataSet data_1("data_1", "dataset with mass (1)", tree_1, RooArgSet(DeltaM,BS));
   RooDataSet data_2("data_2", "dataset with mass (2)", tree_2, RooArgSet(DeltaM,BS));
   RooDataSet data_3("data_3", "dataset with mass (3)", tree_3, RooArgSet(DeltaM,BS));
   RooDataSet data_4("data_4", "dataset with mass (4)", tree_4, RooArgSet(DeltaM,BS));

   // Merge The Datasets
   RooDataSet *mergedData = (RooDataSet*)data_1.Clone(); // Start with data1
   mergedData->append(data_2); // Add data2
   mergedData->append(data_3); // Add data3
   mergedData->append(data_4); // Add data4

    // Apply a cut on the merged dataset
    RooDataSet *filteredData = (RooDataSet*)mergedData->reduce("Ds_extraInfo_BkgBDT >= 0.531 && Ds_diff_D0pi >= 0.16 && Ds_diff_D0pi <= 0.45");
   //=========================================================================================================================================================================//
   // C r e a t e   C o m b i n e d   M o d e l
   // ------------------------------------------------------------------------------
   // // Signal
   // //------------
   // // First Gamma Function
   // RooRealVar x00_S("x00_S","x00_S", 1.6669e-01, 0.16, 0.18);
   // RooRealVar a0_S("a0_S","a0_S", 1.0805e+00, 0.0e+00, 2.0e+00);
   // RooRealVar b0_S("b0_S","b0_S", 7.1333e+00, 6.0e+00, 8.0e+00);    
   // x00_S.setConstant(true);
   // a0_S.setConstant(true);
   // b0_S.setConstant(true);
   // RooFormulaVar x00prime_S("#x00prime_S", "x[0] < x[1] ? x[0] : x[1]", RooArgList(DeltaM, x00_S));     
   // RooFormulaVar gamma0_S("#gamma0_S", "a0_S + 1", RooArgList(a0_S));    
   // RooFormulaVar beta0_for_gamma_S("beta0_for_gamma_S", "1./b0_S", RooArgList(b0_S));    
   // RooGamma GammaModel0_S("GammaModel0_S", "Gamma pdf", DeltaM, gamma0_S, beta0_for_gamma_S, x00prime_S);

   // // Second Gamma Function
   // RooRealVar x01_S("x01_S","x01_S", 1.3936e-01, 0.13, 0.15);
   // RooRealVar a1_S("a1_S","a1_S", 3.4813e+00, 2.0e+00, 4.0e+00);
   // RooRealVar b1_S("b1_S","b1_S", 6.1644e+01, 5.0e+01, 7.0e+01);     
   // x01_S.setConstant(true);
   // a1_S.setConstant(true);
   // b1_S.setConstant(true);
   // RooFormulaVar x01prime_S("#x01prime_S", "x[0] < x[1] ? x[0] : x[1]", RooArgList(DeltaM, x01_S));     
   // RooFormulaVar gamma1_S("#gamma1_S", "a1_S + 1", RooArgList(a1_S));    
   // RooFormulaVar beta1_for_gamma_S("beta1_for_gamma_S", "1./b1_S", RooArgList(b1_S));    
   // RooGamma GammaModel1_S("GammaModel1_S", "Gamma pdf", DeltaM, gamma1_S, beta1_for_gamma_S, x01prime_S);

   // // Second Gamma Function
   // RooRealVar x02_S("x02_S","x02_S", 1.3425e-01, 0.13, 0.14);
   // RooRealVar a2_S("a2_S","a2_S", 5.9167e-01, 5.0e-01, 7.0e-01);
   // RooRealVar b2_S("b2_S","b2_S", 3.9050e+01, 3.0e+01, 5.0e+01);     
   // x02_S.setConstant(true);
   // a2_S.setConstant(true);
   // b2_S.setConstant(true);
   // RooFormulaVar x02prime_S("#x01prime_S", "x[0] < x[1] ? x[0] : x[1]", RooArgList(DeltaM, x02_S));     
   // RooFormulaVar gamma2_S("#gamma2_S", "a2_S + 1", RooArgList(a2_S));    
   // RooFormulaVar beta2_for_gamma_S("beta2_for_gamma_S", "1./b2_S", RooArgList(b2_S));    
   // RooGamma GammaModel2_S("GammaModel2_S", "Gamma pdf", DeltaM, gamma2_S, beta2_for_gamma_S, x02prime_S);

   // // Add the components
   // RooRealVar f0_S("f0_S", "f0", 6.2592e-02, 5.0e-02, 7.0e-02);
   // RooRealVar f1_S("f1_S", "f1", 4.4977e-01, 4.0e-01, 6.0e-01);
   // RooRealVar f2_S("f2_S", "f1", 4.1065e-01, 3.0e-01, 5.0e-01);
   // f0_S.setConstant(true);
   // f1_S.setConstant(true);
   // f2_S.setConstant(true);
   // RooAddPdf SignalModel("SignalModel","g1+g2",RooArgList(GammaModel0_S,GammaModel1_S,GammaModel2_S), RooArgList(f0_S,f1_S,f2_S));

   // // Dstarplus
   // //----------------
   // // Peaking Component
   // //---------------------
   // RooRealVar sig_mean("sig_mean", "mean of crystal", 1.4541e-01, 1.44e-01, 1.46e-01);
   // RooRealVar sig_sigmaL("sig_sigmaL", "sig_sigmaL", 3.0804e-04, 2.0e-4, 4.0e-04);
   // RooRealVar sig_sigmaR("sig_sigmaR", "sig_sigmaR", 3.4151e-04, 2.0e-4, 4.0e-04);
   // RooRealVar sig_alphaL("sig_alphaL", "sig_alphaL", 1.1740e+00, 1e-4, 2.0e+00);
   // RooRealVar sig_alphaR("sig_alphaR", "sig_alphaR", 1.2262e+00, 1e-4, 2.0e+00);
   // RooRealVar sig_nL("sig_nL", "sig_nL", 4.1731e+00, 3.0e+00, 5.0e+00);
   // RooRealVar sig_nR("sig_nR", "sig_nR", 4.1507e+00, 3.0e+00, 5.0e+00);
   //  sig_mean.setConstant();
   //  sig_sigmaL.setConstant();
   //  sig_sigmaR.setConstant();
   //  sig_alphaL.setConstant();
   //  sig_alphaR.setConstant();
   //  sig_nL.setConstant();
   //  sig_nR.setConstant();
   // RooCrystalBall CrystallB("CrystallB", "sig4", DeltaM, sig_mean,sig_sigmaL,sig_sigmaR,sig_alphaL,sig_nL,sig_alphaR,sig_nR);

	// RooRealVar sigmean0_DstarPBkg("sigmean0_DstarPBkg", "mean", 1.3586e-01, 0.135, 0.155);
	// RooRealVar sigwidth0_DstarPBkg("sigwidth0_DstarPBkg", "width", 2.8301e-02, 0, 0.2);
   //  sigmean0_DstarPBkg.setConstant();
   //  sigwidth0_DstarPBkg.setConstant();
	// RooGaussModel gaussm0_DstarPBkg("gaussm0_DstarPBkg", "Signal PDF", DeltaM, sigmean0_DstarPBkg, sigwidth0_DstarPBkg);

	// RooRealVar sigmean1_DstarPBkg("sigmean1_DstarPBkg", "mean", 1.6796e-01, 0.135, 0.17);
	// RooRealVar sigwidth1_DstarPBkg("sigwidth1_DstarPBkg", "width", 5.0222e-06, 0, 0.1);
   //  sigmean1_DstarPBkg.setConstant();
   //  sigwidth1_DstarPBkg.setConstant();
	// RooGaussModel gaussm1_DstarPBkg("gaussm1_DstarPBkg", "Signal PDF", DeltaM, sigmean1_DstarPBkg, sigwidth1_DstarPBkg);

	// RooRealVar sigmean2_DstarPBkg("sigmean2_DstarPBkg", "mean", 1.4986e-01, 0.135, 0.155);
	// RooRealVar sigwidth2_DstarPBkg("sigwidth2_DstarPBkg", "width", 4.1084e-03, 0, 0.1);
   //  sigmean2_DstarPBkg.setConstant();
   //  sigwidth2_DstarPBkg.setConstant();
	// RooGaussModel gaussm2_DstarPBkg("gaussm2_DstarPBkg", "Signal PDF", DeltaM, sigmean2_DstarPBkg, sigwidth2_DstarPBkg);

   // RooRealVar f0_P_DstarPBkg("f0_P_DstarPBkg", "Fraction #1", 9.2342e-01, 0, 1.0);
   // RooRealVar f1_P_DstarPBkg("f1_P_DstarPBkg", "Fraction #1", 1.0490e-07, 0, 1.0);
   // RooRealVar f2_P_DstarPBkg("f2_P_DstarPBkg", "Fraction #1", 1.2650e-08, 0, 1.0);
   // RooRealVar f3_P_DstarPBkg("f3_P_DstarPBkg", "Fraction #1", 1.8303e-02, 0, 1.0);
   // f0_P_DstarPBkg.setConstant();
   // f1_P_DstarPBkg.setConstant();
   // f2_P_DstarPBkg.setConstant();
   // f3_P_DstarPBkg.setConstant();
   // // RooAddPdf PeakingBkgModel("PeakingBkgModel", "Combined Reverse Argus", RooArgList(CrystallB,novosibirsk), RooArgList(f0,f1));
   // RooAddPdf PeakingBkgModel("PeakingBkgModel", "Combined Reverse Argus", RooArgList(CrystallB,gaussm0_DstarPBkg,gaussm1_DstarPBkg,gaussm2_DstarPBkg), RooArgList(f0_P_DstarPBkg,f1_P_DstarPBkg,f2_P_DstarPBkg,f3_P_DstarPBkg));

   // // Combinatorial Part
   // //----------------------
   // // First Gamma Function
   // RooRealVar x00_DstarPBkg("x00_DstarPBkg","x00_DstarPBkg", 1.4563e-01, 0.13, 0.15);
   // RooRealVar a0_DstarPBkg("a0_DstarPBkg","a0_DstarPBkg", 4.7490e-01, 4.0e-01, 6.0e-01);
   // RooRealVar b0_DstarPBkg("b0_DstarPBkg","b0_DstarPBkg", 2.8914e+00, 2.0e+00, 4.0e+00);    
   // x00_DstarPBkg.setConstant();
   // a0_DstarPBkg.setConstant();
   // b0_DstarPBkg.setConstant();
   // RooFormulaVar x00prime_DstarPBkg("#x00prime_DstarPBkg", "x[0] < x[1] ? x[0] : x[1]", RooArgList(DeltaM, x00_DstarPBkg));     
   // RooFormulaVar gamma0_DstarPBkg("#gamma0_DstarPBkg", "a0_DstarPBkg + 1", RooArgList(a0_DstarPBkg));    
   // RooFormulaVar beta0_for_gamma_DstarPBkg("beta0_for_gamma_DstarPBkg", "1./b0_DstarPBkg", RooArgList(b0_DstarPBkg));    
   // RooGamma GammaModel0_DstarPBkg("GammaModel0_DstarPBkg", "Gamma pdf", DeltaM, gamma0_DstarPBkg, beta0_for_gamma_DstarPBkg, x00prime_DstarPBkg);

   // // Second Gamma Function
   // RooRealVar x01_DstarPBkg("x01_DstarPBkg","x01_DstarPBkg", 1.3979e-01, 0.13, 0.15);
   // RooRealVar a1_DstarPBkg("a1_DstarPBkg","a1_DstarPBkg", 3.0289e-01, 2.0e-01, 4.0e-01);
   // RooRealVar b1_DstarPBkg("b1_DstarPBkg","b1_DstarPBkg", 1.0034e+02, 0.0, 500.);     
   // x01_DstarPBkg.setConstant();
   // a1_DstarPBkg.setConstant();
   // b1_DstarPBkg.setConstant();
   // RooFormulaVar x01prime_DstarPBkg("#x01prime_S", "x[0] < x[1] ? x[0] : x[1]", RooArgList(DeltaM, x01_DstarPBkg));     
   // RooFormulaVar gamma1_DstarPBkg("#gamma1_DstarPBkg", "a1_DstarPBkg + 1", RooArgList(a1_DstarPBkg));    
   // RooFormulaVar beta1_for_gamma_DstarPBkg("beta1_for_gamma_DstarPBkg", "1./b1_DstarPBkg", RooArgList(b1_DstarPBkg));    
   // RooGamma GammaModel1_DstarPBkg("GammaModel1_DstarPBkg", "Gamma pdf", DeltaM, gamma1_DstarPBkg, beta1_for_gamma_DstarPBkg, x01prime_DstarPBkg);

   // // Third Gamma Function
   // RooRealVar x02_DstarPBkg("x02_DstarPBkg","x02_DstarPBkg", 1.3512e-01, 0.13, 0.15);
   // RooRealVar a2_DstarPBkg("a2_DstarPBkg","a2_DstarPBkg", 2.2983e+00, 1.0e+00, 3.0e+00);
   // RooRealVar b2_DstarPBkg("b2_DstarPBkg","b2_DstarPBkg", 1.5888e+01, 1.0e+01, 3.0e+01);     
   // x02_DstarPBkg.setConstant();
   // a2_DstarPBkg.setConstant();
   // b2_DstarPBkg.setConstant();
   // RooFormulaVar x02prime_DstarPBkg("#x02prime_S", "x[0] < x[1] ? x[0] : x[1]", RooArgList(DeltaM, x02_DstarPBkg));     
   // RooFormulaVar gamma2_DstarPBkg("#gamma2_DstarPBkg", "a2_DstarPBkg + 1", RooArgList(a2_DstarPBkg));    
   // RooFormulaVar beta2_for_gamma_DstarPBkg("beta2_for_gamma_DstarPBkg", "1./b2_DstarPBkg", RooArgList(b2_DstarPBkg));    
   // RooGamma GammaModel2_DstarPBkg("GammaModel2_DstarPBkg", "Gamma pdf", DeltaM, gamma2_DstarPBkg, beta2_for_gamma_DstarPBkg, x02prime_DstarPBkg);

   // // Add the components
   // RooRealVar f0_DstarPBkg("f0_DstarPBkg", "f0", 1.9359e+00, 0, 2);
   // RooRealVar f1_DstarPBkg("f1_DstarPBkg", "f1", 4.0209e-02, 0, 2);
   // RooRealVar f2_DstarPBkg("f2_DstarPBkg", "f2", 1.3817e+00, 0, 2);
   // // RooRealVar f3_DstarPBkg("f3_DstarPBkg", "f3", 1.7368e+00, 0, 2);
   // f0_DstarPBkg.setConstant();
   // f1_DstarPBkg.setConstant();
   // f2_DstarPBkg.setConstant();
   // // f3_DstarPBkg.setConstant();
   // RooAddPdf CombBkgModel("CombBkgModel","g1+g2",RooArgList(GammaModel0_DstarPBkg,GammaModel1_DstarPBkg,GammaModel2_DstarPBkg), RooArgList(f0_DstarPBkg,f1_DstarPBkg,f2_DstarPBkg));

   // // Total Model
   // // Add the components
   // RooRealVar f_DstarPBkg_Peak("f_DstarPBkg_Peak", "f0", 1.7470e-07, 0, 1);
   // RooRealVar f_DstarPBkg_Comb("f_DstarPBkg_Comb", "f1", 3.9599e-04, 0, 1);
   // f_DstarPBkg_Peak.setConstant();
   // f_DstarPBkg_Comb.setConstant();
   // RooAddPdf DstarPModel("DstarPModel","g1+g2",RooArgList(PeakingBkgModel,CombBkgModel), RooArgList(f_DstarPBkg_Peak,f_DstarPBkg_Comb));

   // // Dstar0
   // //------------------
   // RooRealVar c0_Dstar0Bkg("c0_Dstar0Bkg", "coefficient #0", -3.0114e-01, -1.0, 1.0);
   // RooRealVar c1_Dstar0Bkg("c1_Dstar0Bkg", "coefficient #1", -1.9245e-01, -1.0, 1.0);
   // RooRealVar c2_Dstar0Bkg("c2_Dstar0Bkg", "coefficient #2",  1.5322e-01, -1.0, 1.0);
   // RooRealVar c3_Dstar0Bkg("c3_Dstar0Bkg", "coefficient #3", -6.8649e-02, -1.0, 1.0);
   // RooRealVar c4_Dstar0Bkg("c4_Dstar0Bkg", "coefficient #4",  4.9391e-02, -1.0, 1.0);
   // RooRealVar c5_Dstar0Bkg("c5_Dstar0Bkg", "coefficient #5", -2.0065e-02, -1.0, 1.0);
   // RooRealVar c6_Dstar0Bkg("c6_Dstar0Bkg", "coefficient #6",  1.9927e-03, -1.0, 1.0);
   // RooRealVar c7_Dstar0Bkg("c7_Dstar0Bkg", "coefficient #7",  4.1666e-03, -1.0, 1.0);
   // RooRealVar c8_Dstar0Bkg("c8_Dstar0Bkg", "coefficient #8", -6.0424e-03, -1.0, 1.0);
   // c0_Dstar0Bkg.setConstant(true);
   // c1_Dstar0Bkg.setConstant(true);
   // c2_Dstar0Bkg.setConstant(true);
   // c3_Dstar0Bkg.setConstant(true);
   // c4_Dstar0Bkg.setConstant(true);
   // c5_Dstar0Bkg.setConstant(true);
   // c6_Dstar0Bkg.setConstant(true);
   // c7_Dstar0Bkg.setConstant(true);
   // c8_Dstar0Bkg.setConstant(true);
   // RooChebychev Dstar0BkgModel("Dstar0BkgModel", "Dstar0BkgModel", DeltaM, RooArgList(c0_Dstar0Bkg,c1_Dstar0Bkg,c2_Dstar0Bkg,c3_Dstar0Bkg,c4_Dstar0Bkg,c5_Dstar0Bkg,c6_Dstar0Bkg,c7_Dstar0Bkg,c8_Dstar0Bkg));

   // // D0
   // //---------------
   // RooRealVar c0_D0Bkg("c0_D0Bkg", "coefficient #0", -6.7830e-04, -1.0, 1.0);
   // RooRealVar c1_D0Bkg("c1_D0Bkg", "coefficient #1", -3.7655e-01, -1.0, 1.0);
   // RooRealVar c2_D0Bkg("c2_D0Bkg", "coefficient #2",  1.6824e-01, -1.0, 1.0);
   // RooRealVar c3_D0Bkg("c3_D0Bkg", "coefficient #3", -2.1080e-02, -1.0, 1.0);
   // RooRealVar c4_D0Bkg("c4_D0Bkg", "coefficient #4", -5.6988e-03, -1.0, 1.0);
   // RooRealVar c5_D0Bkg("c5_D0Bkg", "coefficient #5",  1.4470e-02, -1.0, 1.0);
   // RooRealVar c6_D0Bkg("c6_D0Bkg", "coefficient #6", -1.1129e-02, -1.0, 1.0);
   // RooRealVar c7_D0Bkg("c7_D0Bkg", "coefficient #7",  1.0818e-02, -1.0, 1.0);
   // RooRealVar c8_D0Bkg("c8_D0Bkg", "coefficient #8", -1.0832e-02, -1.0, 1.0);
   // c0_D0Bkg.setConstant(true);
   // c1_D0Bkg.setConstant(true);
   // c2_D0Bkg.setConstant(true);
   // c3_D0Bkg.setConstant(true);
   // c4_D0Bkg.setConstant(true);
   // c5_D0Bkg.setConstant(true);
   // c6_D0Bkg.setConstant(true);
   // c7_D0Bkg.setConstant(true);
   // c8_D0Bkg.setConstant(true);
   // RooChebychev D0BkgModel("D0BkgModel", "D0BkgModel", DeltaM, RooArgList(c0_D0Bkg,c1_D0Bkg,c2_D0Bkg,c3_D0Bkg,c4_D0Bkg,c5_D0Bkg,c6_D0Bkg,c7_D0Bkg,c8_D0Bkg));

   // // Other
   // //------------
   // // First Gamma Function
   // RooRealVar x00_FakeD0Bkg("x00_FakeD0Bkg","x00_FakeD0Bkg", 1.5792e-01, 0.13, 0.2);
   // RooRealVar a0_FakeD0Bkg("a0_FakeD0Bkg","a0_FakeD0Bkg", 2.6847e-01, 2.0e-01, 4.0e-01);
   // RooRealVar b0_FakeD0Bkg("b0_FakeD0Bkg","b0_FakeD0Bkg", 8.1515e+00, 7.0e+00, 9.0e+00);    
   // x00_FakeD0Bkg.setConstant();
   // a0_FakeD0Bkg.setConstant();
   // b0_FakeD0Bkg.setConstant();
   // RooFormulaVar x00prime_FakeD0Bkg("#x00prime_FakeD0Bkg", "x[0] < x[1] ? x[0] : x[1]", RooArgList(DeltaM, x00_FakeD0Bkg));     
   // RooFormulaVar gamma0_FakeD0Bkg("#gamma0_FakeD0Bkg", "a0_FakeD0Bkg + 1", RooArgList(a0_FakeD0Bkg));    
   // RooFormulaVar beta0_for_gamma_FakeD0Bkg("beta0_for_gamma_FakeD0Bkg", "1./b0_FakeD0Bkg", RooArgList(b0_FakeD0Bkg));    
   // RooGamma GammaModel0_FakeD0Bkg("GammaModel1_FakeD0Bkg", "Gamma pdf", DeltaM, gamma0_FakeD0Bkg, beta0_for_gamma_FakeD0Bkg, x00prime_FakeD0Bkg);

   // // Second Gamma Function
   // RooRealVar x01_FakeD0Bkg("x01_FakeD0Bkg","x01_FakeD0Bkg", 1.3166e-01, 0.13, 0.2);
   // RooRealVar a1_FakeD0Bkg("a1_FakeD0Bkg","a1_FakeD0Bkg", 3.8644e+00, 3.0e+00, 5.0e+00);
   // RooRealVar b1_FakeD0Bkg("b1_FakeD0Bkg","b1_FakeD0Bkg", 1.6837e+01, 1.0e+01, 3.0e+01);     
   // x01_FakeD0Bkg.setConstant();
   // a1_FakeD0Bkg.setConstant();
   // b1_FakeD0Bkg.setConstant();
   // RooFormulaVar x01prime_FakeD0Bkg("#x01prime_S", "x[0] < x[1] ? x[0] : x[1]", RooArgList(DeltaM, x01_FakeD0Bkg));     
   // RooFormulaVar gamma1_FakeD0Bkg("#gamma1_FakeD0Bkg", "a1_FakeD0Bkg + 1", RooArgList(a1_FakeD0Bkg));    
   // RooFormulaVar beta1_for_gamma_FakeD0Bkg("beta1_for_gamma_FakeD0Bkg", "1./b1_FakeD0Bkg", RooArgList(b1_FakeD0Bkg));    
   // RooGamma GammaModel1_FakeD0Bkg("GammaModel2_FakeD0Bkg", "Gamma pdf", DeltaM, gamma1_FakeD0Bkg, beta1_for_gamma_FakeD0Bkg, x01prime_FakeD0Bkg);

   // // Third Gamma Function
   // RooRealVar x02_FakeD0Bkg("x02_FakeD0Bkg","x02_FakeD0Bkg", 3.7183e-01, 0.13, 0.5);
   // RooRealVar a2_FakeD0Bkg("a2_FakeD0Bkg","a2_FakeD0Bkg", 2.7283e+01, 2.0e+01, 4.0e+01);
   // RooRealVar b2_FakeD0Bkg("b2_FakeD0Bkg","b2_FakeD0Bkg", 1.7067e+02, 1.0e+02, 3.0e+02);     
   // x02_FakeD0Bkg.setConstant();
   // a2_FakeD0Bkg.setConstant();
   // b2_FakeD0Bkg.setConstant();
   // RooFormulaVar x02prime_FakeD0Bkg("#x02prime_S", "x[0] < x[1] ? x[0] : x[1]", RooArgList(DeltaM, x02_FakeD0Bkg));     
   // RooFormulaVar gamma2_FakeD0Bkg("#gamma2_FakeD0Bkg", "a2_FakeD0Bkg + 1", RooArgList(a2_FakeD0Bkg));    
   // RooFormulaVar beta2_for_gamma_FakeD0Bkg("beta2_for_gamma_FakeD0Bkg", "1./b2_FakeD0Bkg", RooArgList(b2_FakeD0Bkg));    
   // RooGamma GammaModel2_FakeD0Bkg("GammaModel3_FakeD0Bkg", "Gamma pdf", DeltaM, gamma2_FakeD0Bkg, beta2_for_gamma_FakeD0Bkg, x02prime_FakeD0Bkg);

   // // Add the components
   // RooRealVar f0_FakeD0Bkg("f0_FakeD0Bkg", "f0", 1.0592e+00, 0.5e+00, 2.0e+00);
   // RooRealVar f1_FakeD0Bkg("f1_FakeD0Bkg", "f1", 9.6705e-01, 9.0e-01, 11.0e-01);
   // RooRealVar f2_FakeD0Bkg("f2_FakeD0Bkg", "f2", 9.9090e-02, 9.0e-02, 11.0e-02);
   // f0_FakeD0Bkg.setConstant();
   // f1_FakeD0Bkg.setConstant();
   // f2_FakeD0Bkg.setConstant();
   // RooAddPdf OtherModel("OtherModel","g1+g2",RooArgList(GammaModel0_FakeD0Bkg,GammaModel1_FakeD0Bkg,GammaModel2_FakeD0Bkg), RooArgList(f0_FakeD0Bkg,f1_FakeD0Bkg,f2_FakeD0Bkg));
   
   //--------------- Combined Model of signal and generic MC ------------------//
   //--------------------------------------------------------------------------//
   RooRealVar f0("f0", "f0", 0, -100., 100.);
   RooRealVar f1("f1", "f1", 7.3635e+04, 6.0e+04, 9.0e+04);
   RooRealVar f2("f2", "f2", 1.4364e+05, 1.0e+05, 2.0e+05);
   RooRealVar f3("f3", "f3", 5.6158e+04, 5.0e+04, 6.0e+04);
   RooRealVar f4("f4", "f4", 9.5978e+03, 8.0e+03, 11.0e+03);

//    RooRealVar f1("f1", "f1", 90068, 8.0e+04, 10.0e+04);
//    RooRealVar f2("f2", "f2", 172933, 1.0e+05, 2.0e+05);
//    RooRealVar f3("f3", "f3", 70299, 6.5e+04, 7.5e+04);
//    RooRealVar f4("f4", "f4", 5329, 3.5e+03, 6.0e+05);
   // f0.setConstant(true);
   // f1.setConstant(true);
   // f2.setConstant(true);
   // f3.setConstant(true);
   // f4.setConstant(true);
   // RooAddPdf model("model", "s+pbkg+cbkg+fs", RooArgList(SignalModel,PeakingBkgModel,CFBkgModel,FakeSignalModel,OtherModel), RooArgList(f0,f1,f2,f3,f4));
   // RooAddPdf model("model", "s+pbkg+cbkg+fs", RooArgList(*SignalModel,*DstarPModel), RooArgList(f0,f1));
   // RooAddPdf model("model", "s+pbkg+cbkg+fs", RooArgList(*SignalModel,*Dstar0BkgModel), RooArgList(f0,f2));
   // RooAddPdf model("model", "s+pbkg+cbkg+fs", RooArgList(*SignalModel,*D0BkgModel), RooArgList(f0,f3));
   // RooAddPdf model("model", "s+pbkg+cbkg+fs", RooArgList(*SignalModel,*OtherModel), RooArgList(f0,f4));
   // RooAddPdf model("model", "s+pbkg+Dstar0+D0+fD0", RooArgList(*DstarPModel,*Dstar0BkgModel,*D0BkgModel,*OtherModel), RooArgList(f1,f2,f3,f4));
   RooAddPdf model("model", "s+pbkg+Dstar0+D0+fD0", RooArgList(*SignalModel,*DstarPModel,*Dstar0BkgModel,*D0BkgModel,*OtherModel), RooArgList(f0,f1,f2,f3,f4));
   // RooAddPdf model("model", "s+pbkg+Dstar0+D0+fD0", RooArgList(SignalModel,DstarPModel,Dstar0BkgModel,D0BkgModel,OtherModel), RooArgList(f0,f1,f2,f3,f4));
   //=========================================================================================================================================================================//
   // // G a u s s i a n    C o n s t r a i n t
   // //--------------------------------------------------------------------------
   // // External knowledge from MC or control regions
   // RooRealVar f1_mean("f1_mean", "MC expectation for f1", 90068);
   // RooRealVar f1_sigma("f1_sigma", "Uncertainty on f1", 300); // adjust as needed

   // RooRealVar f2_mean("f2_mean", "MC expectation for f2", 172933);
   // RooRealVar f2_sigma("f2_sigma", "Uncertainty on f2", 415);

   // RooRealVar f3_mean("f3_mean", "MC expectation for f3", 70299);
   // RooRealVar f3_sigma("f3_sigma", "Uncertainty on f3", 265);

   // RooRealVar f4_mean("f4_mean", "MC expectation for f4", 5329);
   // RooRealVar f4_sigma("f4_sigma", "Uncertainty on f4", 73);

   // RooGaussian f1_constraint("f1_constraint", "Constraint on f1", f1, f1_mean, f1_sigma);
   // RooGaussian f2_constraint("f2_constraint", "Constraint on f2", f2, f2_mean, f2_sigma);
   // RooGaussian f3_constraint("f3_constraint", "Constraint on f3", f3, f3_mean, f3_sigma);
   // RooGaussian f4_constraint("f4_constraint", "Constraint on f4", f4, f4_mean, f4_sigma);   
   //=========================================================================================================================================================================//
   // F i t
   //-------------
   // Perform extended ML fit of data:
   std::unique_ptr<RooFitResult> r{model.fitTo(*filteredData, Save(), PrintLevel(-1), Range(xL,xR))};
   // std::unique_ptr<RooFitResult> r{
   //    model.fitTo(*filteredData,
   //                Save(),
   //                PrintLevel(-1),
   //                Range(xL,xR),
   //                ExternalConstraints(RooArgSet(f1_constraint, f2_constraint, f3_constraint, f4_constraint)))
   // };
   // If the fit is too broad and does not seem to fit a peak use the code below. Use it
   // once to determine where the peak should be and then adjust the mean above.
   //=========================================================================================================================================================================//
   // P l o t 
   //---------
   // // Create binning object with range (0.1,0.55)
   // RooBinning tbins(xL, xR);
 
   // // Add 60 bins with uniform spacing in range (0.1,0.16)
   // tbins.addUniform(50, xL, 0.16);
 
   // // Add 15 bins with uniform spacing in range (0.15,0.55)
   // tbins.addUniform(20, 0.16, xR);

   RooPlot* frame = DeltaM.frame();
   *filteredData->plotOn(frame, Binning(bin));

   double scaleFactor = -5000.0;
   SignalModel->plotOn(frame,
                       Normalization(f0.getVal() * scaleFactor, RooAbsReal::NumEvent),
                       LineStyle(kDashed),
                       LineColor(kAzure-2),
                       RooFit::Name("SignalScaled"));

   model.plotOn(frame, Components(*DstarPModel),     LineStyle(kDashed), LineColor(kGreen+1),    RooFit::Name("DstarP"));
   model.plotOn(frame, Components(*Dstar0BkgModel),  LineStyle(kDashed), LineColor(kOrange+8),   RooFit::Name("Dstar0"));
   model.plotOn(frame, Components(*D0BkgModel),      LineStyle(kDashed), LineColor(kViolet-3),   RooFit::Name("D0"));
   model.plotOn(frame, Components(*OtherModel),      LineStyle(kDashed), LineColor(kOrange-7),   RooFit::Name("Other"));

   // model.plotOn(frame, Components(SignalModel),     LineStyle(kDashed), LineColor(kAzure-2),    RooFit::Name("Signal"));
   // model.plotOn(frame, Components(DstarPModel),     LineStyle(kDashed), LineColor(kGreen+1),    RooFit::Name("DstarP"));
   // model.plotOn(frame, Components(Dstar0BkgModel),  LineStyle(kDashed), LineColor(kOrange+8),   RooFit::Name("Dstar0"));
   // model.plotOn(frame, Components(D0BkgModel),      LineStyle(kDashed), LineColor(kViolet-3),   RooFit::Name("D0"));
   // model.plotOn(frame, Components(OtherModel),      LineStyle(kDashed), LineColor(kOrange-7),   RooFit::Name("Other"));

   model.plotOn(frame, LineColor(41), RooFit::Name("model"));
   // *PeakingBkgModel->plotOn(frame, LineColor(38), RooFit::Name("model"));
   //=========================================================================================================================================================================//
   // C a l c u l a t e   c h i ^ 2
   // ------------------------------
   // Show the chi^2 of the curve w.r.t. the histogram
   // If multiple curves or datasets live in the frame you can specify
   // the name of the relevant curve and/or dataset in chiSquare()
   Int_t npar = model.getParameters(*filteredData)->selectByAttrib("Constant",kFALSE)->getSize(); //select floating parameters and count their number

   cout << "NDF = " << npar << endl;
   cout << "chi^2/NDF = " << frame->chiSquare(npar) << endl;

   Double_t chi2ndf = frame->chiSquare(npar);
   //=========================================================================================================================================================================//
   // P l o t    L a b e l s
   // ---------------------------------------------------------------------------
   // Add text to frame
   TLatex *latex = new TLatex();
   TString lum ("");
   lum.Form("#splitline{Generic Events}{#scale[0.5]{#int}#it{L} dt=1.44 ab^{-1}}");
   // lum.Form("#splitline{Generic c#bar{c} Events}{#scale[0.5]{#int}#it{L} dt=200 fb^{-1}}");
   latex->SetNDC();
   latex->SetTextSize(0.03); 
   
   // // Add "chi-squared fit" below "2M Events"
   // TString chi_label ("");
   // chi_label.Form("#splitline{}{Likelihood Fit}");

   auto PerBin = ((xR-xL)/(bin))*1000;
   // TString title ("");
   TString y_axis ("");
   // TString x_axis ("");

   // title.Form("Generic d#bar{d} Events");
   y_axis.Form("Entries/(%.2f MeV/c^{2})", PerBin);
   // x_axis.Form("#Delta m  [GeV/c^{2}]");

   frame->SetTitle("");
   frame->GetYaxis()->SetTitle(y_axis);
   frame->GetXaxis()->SetTitle("");
   // frame->GetXaxis()->CenterTitle(true);
   // pad1->SetLogx();
   // Set log scale for Y-axis
   // pad1->SetLogy();

   // Ensure Y-range is properly set
   // frame->GetYaxis()->SetRangeUser(1, 10e+05); // Log scale cannot have 0
   frame->GetYaxis()->SetRangeUser(0,15000);
   frame->Draw();

   // The line below prints the luminosity onto the screen.
   // latex->DrawLatex(0.6,0.2, lum);
   latex->DrawLatex(0.2,0.89, lum);
   // latex->DrawLatex(0.18,0.85, chi_label);
   //=========================================================================================================================================================================//
   // P a r a m e t e r   B o x
   // ---------------------------------------------------------------------------
   auto xIF1 = pad1 -> GetUxmin() + pad1 -> GetLeftMargin();
   auto xIF2 = pad1 -> GetUxmax() - pad1 -> GetRightMargin();
   auto yIF1 = pad1 -> GetUymin() + pad1 -> GetBottomMargin();
   auto yIF2 = pad1 -> GetUymax() - pad1 -> GetTopMargin();
   auto dx = xIF2 - xIF1;
   auto dy = yIF2 - yIF1;
   auto x1 = xIF1 + 0.35*dx;
   // auto x1 = xIF1 + 0.55*dx;
   auto x2 = 0.92 ;
   auto y1 = yIF1 + 0.7*dy;
   auto y2 = 0.93;
   auto legend = new TLegend(x1, y1, x2, y2);

   TString chi2("");
   TString N_sig("");
   TString N_DstarP("");
   TString N_Dstar0("");
   TString N_D0("");
   TString N_O("");

   chi2.Form("#chi^{2}/ndf = %.2f", chi2ndf);
   N_sig.Form("N_{sig} = %.2f #pm %.2f", f0.getValV(), f0.getError());
   N_DstarP.Form("N_{D^{*+}} = %.2f #pm %.2f", f1.getValV(), f1.getError());
   N_Dstar0.Form("N_{D^{*0}} = %.2f #pm %.2f", f2.getValV(), f2.getError());
   N_D0.Form("N_{D^{0}} = %.2f #pm %.2f", f3.getValV(), f3.getError());
   N_O.Form("N_{Other} = %.2f #pm %.2f", f4.getValV(), f4.getError());

   // Legend
   // legend->AddEntry(frame->FindObject("data"),"data","pe");
   // legend->AddEntry((TObject *)0, chi2, "");
   
   // TString scaledSignal;
   // scaledSignal.Form("Signal Fit (x%.0f)", scaleFactor);
   // legend->AddEntry("SignalScaled", scaledSignal, "pl");

   // legend->AddEntry((TObject *)0, N_sig, "");
   // legend->AddEntry("DstarP", "D^{*+} #rightarrow D^{0} #pi^{+}", "pl" );
   // legend->AddEntry((TObject *)0, N_DstarP, "");
   // legend->AddEntry("Dstar0", "D^{*0} #rightarrow D^{0} #pi^{0}/#gamma", "pl" );
   // legend->AddEntry((TObject *)0, N_Dstar0, "");
   // legend->AddEntry("D0", "D^{0}", "pl" );
   // legend->AddEntry((TObject *)0, N_D0, "");
   // legend->AddEntry("Other", "Other", "pl" );
   // legend->AddEntry((TObject *)0, N_O, "");
   // legend->AddEntry("model", "Total Fit", "pl" );
   //
   legend->AddEntry(frame->FindObject("data"),"data","pe");
   legend->AddEntry((TObject *)0, chi2, "");

   TString scaledSignal;
   scaledSignal.Form("Signal Fit (x%.0f)", scaleFactor);
   legend->AddEntry("SignalScaled", scaledSignal, "pl");

   legend->AddEntry((TObject *)0, "", "");
   legend->AddEntry("DstarP", "D^{*+} #rightarrow D^{0} #pi^{+}", "pl" );
   legend->AddEntry((TObject *)0, "", "");
   legend->AddEntry("Dstar0", "D^{*0} #rightarrow D^{0} #pi^{0}/#gamma", "pl" );
   legend->AddEntry((TObject *)0, "", "");
   legend->AddEntry("D0", "D^{0}", "pl" );
   legend->AddEntry((TObject *)0, "", "");
   legend->AddEntry("Other", "Other", "pl" );
   legend->AddEntry((TObject *)0, "", "");
   legend->AddEntry("model", "Total Fit", "pl" );

   legend -> SetBorderSize(0);
   legend -> SetTextFont(132);
   legend -> SetTextSize(0.03);
   legend -> SetNColumns(2);
   // legend -> SetNColumns(1);
   legend -> SetMargin(0.1);
   legend->Draw();
   //=========================================================================================================================================================================//
   // S h o w   P a r a m e t e r/ F i t    R e s u l t s
   // -------------------------------------------------------
   // When I use rooworkspace this first part will make sure that the parameters of the 
   // model will stay fixed.
   // N.setConstant(true);
   // N.removeError();
   // b.setConstant(true);
   // b.removeError();
   // P.setConstant(true);
   // P.removeError();

   // Verbose printing: Basic info, values of constant parameters, initial and
   // final values of floating parameters, global correlations
   r->Print("v");

   // Access basic information
   cout << "EDM = " << r->edm() << endl;
   cout << "-log(L) at minimum = " << r->minNll() << endl;

   // Extract covariance and correlation matrix as TMatrixDSym
   const TMatrixDSym &cor = r->correlationMatrix();
   const TMatrixDSym &cov = r->covarianceMatrix();
 
   // Print correlation, covariance matrix
   cout << "Correlation Matrix" << endl;
   cor.Print();
   cout << "Covariance Matrix" << endl;
   cov.Print();
   //=========================================================================================================================================================================//
   // S h o w   P u l l   d i s t s
   // -------------------------------------------------------
   pad2->cd();
   // Construct a histogram with the residuals of the data w.r.t. the curve
   RooHist *hpull = frame->pullHist();
   for(int iPoint = 0; iPoint < hpull->GetN(); ++iPoint) {
      hpull->SetPointEYlow(iPoint, 0.0);
      hpull->SetPointEYhigh(iPoint, 0.0);
   }
   hpull->SetFillColor(38);
   // hpull->SetLineWidth(-802);
   // hpull->SetFillStyle(3002);
   // hpull->SetFillColor(2);

   // Create a new frame to draw the residual distribution and add the distribution to the frame
   RooPlot *frame1 = DeltaM.frame(Title("Pull Distribution"));
   frame1->addPlotable(hpull, "B");
   frame1->Draw();
   
   // Plot Titles
   //---------------
   frame1->SetTitle("");

   // Y-axis
   frame1->SetYTitle("Pull");
   frame1->GetYaxis()->CenterTitle(true);
   frame1->GetYaxis()->SetTitleSize(0.10);
   frame1->GetYaxis()->SetLabelSize(0.10);

   // X-axis
   TString x_axis ("");
   x_axis.Form("#Delta m  [GeV/c^{2}]");
   frame1->SetXTitle(x_axis);
   frame1->GetXaxis()->CenterTitle(true);
   frame1->GetXaxis()->SetTitleSize(0.13);
   frame1->GetXaxis()->SetLabelSize(0.10);

   frame1->SetTitleOffset(0.5, "Y");

   // Draw Horizontal Line On Residual Plot
   //----------------------------------------
   // double xmin1 = xIF1; 
   // double xmax1 = 1.0;
   // TLine *line11 = new TLine(xIF1,0.0,xIF2,0.0);
   // line11->SetLineColor(kRed); line11->SetLineWidth(3);
   // line11->Draw("SAME");

   c->cd();
   //=========================================================================================================================================================================//
   // S a v e   t h e   P l o t 
   //-------------------------------
   c->SaveAs("/home/belle2/amubarak/Ds2D0enue_Analysis/10-Save/Roofit_Suggestion_Likehood_Window/Fit_Image/rs05_DeltaM_Combined.png");
   //=========================================================================================================================================================================//
   // Uncertainty Calculations
   //---------------------------------------------
   Float_t LumS = 400e15;
   Float_t Lum = 1443.999e15;
   Float_t Cross = 1.329e-9;
   Float_t cDs = 0.10;
   Float_t D0 = 0.03947;
   Float_t Efficiency = 0.056864;

   Float_t Central = (f0.getValV())/(Lum*Cross*2*cDs*D0*Efficiency);
   Float_t UpperLimit = (f0.getError())/(Lum*Cross*2*cDs*D0*Efficiency);

   cout << endl << "Central= " << Central << endl;
   cout << "Upper Limit 68% Confidence= " << UpperLimit << endl;
   cout << "Upper Limit 95% Confidence= " << 2*UpperLimit << endl;

   cout << endl << "Total= " << (f1.getValV() + f2.getValV() + f3.getValV() + f4.getValV()) << endl << endl;
   //=========================================================================================================================================================================//
   // Final Fit Status
   //---------------------------
   int fitStatus = r->status();  // Get the fit status
   int covQual = r->covQual();   // Get covariance quality

   std::cout << "Fit Status: " << fitStatus << std::endl;
   std::cout << "Covariance Matrix Quality: " << covQual << std::endl << endl;

}