#include "RooRealVar.h"
#include "RooDataSet.h"
#include "RooGaussian.h"
#include "RooChebychev.h"
#include "RooAddPdf.h"
#include "RooWorkspace.h"
#include "RooPlot.h"
#include "TCanvas.h"
#include "TAxis.h"
#include "TFile.h"
#include "TH1.h"
using namespace RooFit;
 
void rs10_Contour()
{
   // S e t u p   t h e   F r a m e   f o r   t h e   P l o t
   //------------------------------------------------------------
   TCanvas *c = new TCanvas("fit", "fit", 650, 700);
   TPad *pad1 = new TPad("pad1","pad1",0,0.25,1,1);
   TPad *pad2 = new TPad("pad2","pad2",0,0,1,0.25);
   pad1->SetTopMargin(0.05);
   pad1->SetBottomMargin(0.05);
   pad1->SetLeftMargin(0.15);
   pad1->SetRightMargin(0.05);
   pad2->SetLeftMargin(0.15);
   pad2->SetRightMargin(0.05);
   pad2->SetTopMargin(0.01);
   pad2->SetBottomMargin(0.4);
   // pad2->SetBorderMode(0);
   pad1->Draw();
   pad2->Draw();
   pad1->cd();
   gStyle->SetOptStat(0);
   //=========================================================================================================================================================================//
   // // R e a d   w o r k s p a c e   f r o m   f i l e
   // // -----------------------------------------------
   // // Open input file with workspace (generated by rf503_wspacewrite)
   // TFile *f_S = new TFile("/home/belle2/amubarak/Ds2D0enue_Analysis/10-Suggestion/Roofit_Suggestion_Likehood_Window/Fit_Parameter/rs00_SignalPara.root");
   // TFile *f_DstarP = new TFile("/home/belle2/amubarak/Ds2D0enue_Analysis/10-Suggestion/Roofit_Suggestion_Likehood_Window/Fit_Parameter/rs01_DstarP.root");
   // TFile *f_Dstar0 = new TFile("/home/belle2/amubarak/Ds2D0enue_Analysis/10-Suggestion/Roofit_Suggestion_Likehood_Window/Fit_Parameter/rs02_Dstar0.root");
   // TFile *f_D0 = new TFile("/home/belle2/amubarak/Ds2D0enue_Analysis/10-Suggestion/Roofit_Suggestion_Likehood_Window/Fit_Parameter/rs03_D0.root");
   // TFile *f_O = new TFile("/home/belle2/amubarak/Ds2D0enue_Analysis/10-Suggestion/Roofit_Suggestion_Likehood_Window/Fit_Parameter/rs04_OtherPara.root");
 
   // // R e t r i e v e   p d f   f r o m   w o r k s p a c e
   // // -----------------------------------------------------------------
   // // Signal
   // RooWorkspace *w_S = (RooWorkspace *)f_S->Get("w_S");
   // // RooRealVar *M_S = w_S->var("Ds_diff_D0pi");
   // RooAbsPdf *SignalModel = w_S->pdf("SignalModel");

   // // Peaking Background
   // RooWorkspace *w_DstarP = (RooWorkspace *)f_DstarP->Get("w_PBkg");
   // // RooRealVar *M_PBkg = w_PBkg->var("Ds_diff_D0pi");
   // RooAbsPdf *DstarPModel = w_DstarP->pdf("DstarPModel");

   // // Combinatorial + Failed Background
   // RooWorkspace *w_Dstar0 = (RooWorkspace *)f_Dstar0->Get("w_Dstar0");
   // // RooRealVar *M_CFBkg = w_CFBkg->var("Ds_diff_D0pi");
   // RooAbsPdf *Dstar0BkgModel = w_Dstar0->pdf("Dstar0BkgModel");

   // // Fake Signal
   // RooWorkspace *w_D0 = (RooWorkspace *)f_D0->Get("w_D0");
   // // RooRealVar *M_CFBkg = w_CFBkg->var("Ds_diff_D0pi");
   // RooAbsPdf *D0BkgModel = w_D0->pdf("D0BkgModel");

   // // Other
   // RooWorkspace *w_O = (RooWorkspace *)f_O->Get("w_O");
   // // RooRealVar *M_OBkg = w_CFBkg->var("Ds_diff_D0pi");
   // RooAbsPdf *OtherModel = w_O->pdf("OtherModel");

   // w_S->loadSnapshot("reference_fit_Signal");
   // w_DstarP->loadSnapshot("reference_fit_PeakingBkg");
   // w_Dstar0->loadSnapshot("reference_fit_Dstar0_Bkg");
   // w_D0->loadSnapshot("reference_fit_D0");
   // w_O->loadSnapshot("reference_fit_Other");
   //=========================================================================================================================================================================//
   // I n i t i a l i z a t i o n:
   // --------------------------------------------------------------
   // The lines below initializes all my values
   int bin = 50;
   double xL = 0.16;
   double xR = 0.55;
   //=========================================================================================================================================================================//
   // I m p o r t s   D a t a   f r o m   t r e e   b r a n c h:
   // --------------------------------------------------------------
   // Total Viewing
   // TFile *file = new TFile("/group/belle2/users2022/amubarak/02-Grid/Completed_TopoAna/Ds2D0e-Generic_Ds_021325_2_ccbar.root");
   // TTree *tree = (TTree*)file->Get("Dstree");
   // Individual Viewing
   TFile *file = new TFile("/home/belle2/amubarak/C03-Grid/TopoAna.root");
   TTree *tree_1 = (TTree*)file->Get("Dstarplus");
   TTree *tree_2 = (TTree*)file->Get("Dstar0");
   TTree *tree_3 = (TTree*)file->Get("D0");
   TTree *tree_4 = (TTree*)file->Get("FakeD0");
   //=========================================================================================================================================================================//
   // D a t a:
   // --------------------------------------------------------------
   RooRealVar DeltaM("Ds_diff_D0pi", "Mass Difference", xL, xR);
   RooRealVar BS("Ds_extraInfo_BkgBDT", "Background Suppression", 0.0, 1.0);

   RooDataSet data_1("data_1", "dataset with mass (1)", tree_1, RooArgSet(DeltaM,BS));
   RooDataSet data_2("data_2", "dataset with mass (2)", tree_2, RooArgSet(DeltaM,BS));
   RooDataSet data_3("data_3", "dataset with mass (3)", tree_3, RooArgSet(DeltaM,BS));
   RooDataSet data_4("data_4", "dataset with mass (4)", tree_4, RooArgSet(DeltaM,BS));

   // Merge The Datasets
   RooDataSet *mergedData = (RooDataSet*)data_1.Clone(); // Start with data1
   mergedData->append(data_2); // Add data2
   mergedData->append(data_3); // Add data3
   mergedData->append(data_4); // Add data4

    // Apply a cut on the merged dataset
    RooDataSet *filteredData = (RooDataSet*)mergedData->reduce("Ds_extraInfo_BkgBDT >= 0.531 && Ds_diff_D0pi >= 0.16 && Ds_diff_D0pi <= 0.55");
   //=========================================================================================================================================================================//
   // C r e a t e   C o m b i n e d   M o d e l
   // ------------------------------------------------------------------------------
   // Signal
   //------------
   // First Gamma Function
   RooRealVar x00_S("x00_S","x00_S", 1.6669e-01, 0.16, 0.18);
   RooRealVar a0_S("a0_S","a0_S", 1.0805e+00, 0.0e+00, 2.0e+00);
   RooRealVar b0_S("b0_S","b0_S", 7.1333e+00, 6.0e+00, 8.0e+00);    
   x00_S.setConstant(true);
   a0_S.setConstant(true);
   b0_S.setConstant(true);
   RooFormulaVar x00prime_S("#x00prime_S", "x[0] < x[1] ? x[0] : x[1]", RooArgList(DeltaM, x00_S));     
   RooFormulaVar gamma0_S("#gamma0_S", "a0_S + 1", RooArgList(a0_S));    
   RooFormulaVar beta0_for_gamma_S("beta0_for_gamma_S", "1./b0_S", RooArgList(b0_S));    
   RooGamma GammaModel0_S("GammaModel0_S", "Gamma pdf", DeltaM, gamma0_S, beta0_for_gamma_S, x00prime_S);

   // Second Gamma Function
   RooRealVar x01_S("x01_S","x01_S", 1.3936e-01, 0.13, 0.15);
   RooRealVar a1_S("a1_S","a1_S", 3.4813e+00, 2.0e+00, 4.0e+00);
   RooRealVar b1_S("b1_S","b1_S", 6.1644e+01, 5.0e+01, 7.0e+01);     
   x01_S.setConstant(true);
   a1_S.setConstant(true);
   b1_S.setConstant(true);
   RooFormulaVar x01prime_S("#x01prime_S", "x[0] < x[1] ? x[0] : x[1]", RooArgList(DeltaM, x01_S));     
   RooFormulaVar gamma1_S("#gamma1_S", "a1_S + 1", RooArgList(a1_S));    
   RooFormulaVar beta1_for_gamma_S("beta1_for_gamma_S", "1./b1_S", RooArgList(b1_S));    
   RooGamma GammaModel1_S("GammaModel1_S", "Gamma pdf", DeltaM, gamma1_S, beta1_for_gamma_S, x01prime_S);

   // Second Gamma Function
   RooRealVar x02_S("x02_S","x02_S", 1.3425e-01, 0.13, 0.14);
   RooRealVar a2_S("a2_S","a2_S", 5.9167e-01, 5.0e-01, 7.0e-01);
   RooRealVar b2_S("b2_S","b2_S", 3.9050e+01, 3.0e+01, 5.0e+01);     
   x02_S.setConstant(true);
   a2_S.setConstant(true);
   b2_S.setConstant(true);
   RooFormulaVar x02prime_S("#x01prime_S", "x[0] < x[1] ? x[0] : x[1]", RooArgList(DeltaM, x02_S));     
   RooFormulaVar gamma2_S("#gamma2_S", "a2_S + 1", RooArgList(a2_S));    
   RooFormulaVar beta2_for_gamma_S("beta2_for_gamma_S", "1./b2_S", RooArgList(b2_S));    
   RooGamma GammaModel2_S("GammaModel2_S", "Gamma pdf", DeltaM, gamma2_S, beta2_for_gamma_S, x02prime_S);

   // Add the components
   RooRealVar f0_S("f0_S", "f0", 6.2592e-02, 5.0e-02, 7.0e-02);
   RooRealVar f1_S("f1_S", "f1", 4.4977e-01, 4.0e-01, 6.0e-01);
   RooRealVar f2_S("f2_S", "f1", 4.1065e-01, 3.0e-01, 5.0e-01);
   f0_S.setConstant(true);
   f1_S.setConstant(true);
   f2_S.setConstant(true);
   RooAddPdf SignalModel("SignalModel","g1+g2",RooArgList(GammaModel0_S,GammaModel1_S,GammaModel2_S), RooArgList(f0_S,f1_S,f2_S));

   // Dstarplus
   //----------------
   // Peaking Component
   //---------------------
   RooRealVar sig_mean("sig_mean", "mean of crystal", 1.4541e-01, 1.44e-01, 1.46e-01);
   RooRealVar sig_sigmaL("sig_sigmaL", "sig_sigmaL", 3.0804e-04, 2.0e-4, 4.0e-04);
   RooRealVar sig_sigmaR("sig_sigmaR", "sig_sigmaR", 3.4151e-04, 2.0e-4, 4.0e-04);
   RooRealVar sig_alphaL("sig_alphaL", "sig_alphaL", 1.1740e+00, 1e-4, 2.0e+00);
   RooRealVar sig_alphaR("sig_alphaR", "sig_alphaR", 1.2262e+00, 1e-4, 2.0e+00);
   RooRealVar sig_nL("sig_nL", "sig_nL", 4.1731e+00, 3.0e+00, 5.0e+00);
   RooRealVar sig_nR("sig_nR", "sig_nR", 4.1507e+00, 3.0e+00, 5.0e+00);
    sig_mean.setConstant();
    sig_sigmaL.setConstant();
    sig_sigmaR.setConstant();
    sig_alphaL.setConstant();
    sig_alphaR.setConstant();
    sig_nL.setConstant();
    sig_nR.setConstant();
   RooCrystalBall CrystallB("CrystallB", "sig4", DeltaM, sig_mean,sig_sigmaL,sig_sigmaR,sig_alphaL,sig_nL,sig_alphaR,sig_nR);

	RooRealVar sigmean0_DstarPBkg("sigmean0_DstarPBkg", "mean", 1.3586e-01, 0.135, 0.155);
	RooRealVar sigwidth0_DstarPBkg("sigwidth0_DstarPBkg", "width", 2.8301e-02, 0, 0.2);
    sigmean0_DstarPBkg.setConstant();
    sigwidth0_DstarPBkg.setConstant();
	RooGaussModel gaussm0_DstarPBkg("gaussm0_DstarPBkg", "Signal PDF", DeltaM, sigmean0_DstarPBkg, sigwidth0_DstarPBkg);

	RooRealVar sigmean1_DstarPBkg("sigmean1_DstarPBkg", "mean", 1.6796e-01, 0.135, 0.17);
	RooRealVar sigwidth1_DstarPBkg("sigwidth1_DstarPBkg", "width", 5.0222e-06, 0, 0.1);
    sigmean1_DstarPBkg.setConstant();
    sigwidth1_DstarPBkg.setConstant();
	RooGaussModel gaussm1_DstarPBkg("gaussm1_DstarPBkg", "Signal PDF", DeltaM, sigmean1_DstarPBkg, sigwidth1_DstarPBkg);

	RooRealVar sigmean2_DstarPBkg("sigmean2_DstarPBkg", "mean", 1.4986e-01, 0.135, 0.155);
	RooRealVar sigwidth2_DstarPBkg("sigwidth2_DstarPBkg", "width", 4.1084e-03, 0, 0.1);
    sigmean2_DstarPBkg.setConstant();
    sigwidth2_DstarPBkg.setConstant();
	RooGaussModel gaussm2_DstarPBkg("gaussm2_DstarPBkg", "Signal PDF", DeltaM, sigmean2_DstarPBkg, sigwidth2_DstarPBkg);

   RooRealVar f0_P_DstarPBkg("f0_P_DstarPBkg", "Fraction #1", 9.2342e-01, 0, 1.0);
   RooRealVar f1_P_DstarPBkg("f1_P_DstarPBkg", "Fraction #1", 1.0490e-07, 0, 1.0);
   RooRealVar f2_P_DstarPBkg("f2_P_DstarPBkg", "Fraction #1", 1.2650e-08, 0, 1.0);
   RooRealVar f3_P_DstarPBkg("f3_P_DstarPBkg", "Fraction #1", 1.8303e-02, 0, 1.0);
   f0_P_DstarPBkg.setConstant();
   f1_P_DstarPBkg.setConstant();
   f2_P_DstarPBkg.setConstant();
   f3_P_DstarPBkg.setConstant();
   // RooAddPdf PeakingBkgModel("PeakingBkgModel", "Combined Reverse Argus", RooArgList(CrystallB,novosibirsk), RooArgList(f0,f1));
   RooAddPdf PeakingBkgModel("PeakingBkgModel", "Combined Reverse Argus", RooArgList(CrystallB,gaussm0_DstarPBkg,gaussm1_DstarPBkg,gaussm2_DstarPBkg), RooArgList(f0_P_DstarPBkg,f1_P_DstarPBkg,f2_P_DstarPBkg,f3_P_DstarPBkg));

   // Combinatorial Part
   //----------------------
   // First Gamma Function
   RooRealVar x00_DstarPBkg("x00_DstarPBkg","x00_DstarPBkg", 1.4563e-01, 0.13, 0.15);
   RooRealVar a0_DstarPBkg("a0_DstarPBkg","a0_DstarPBkg", 4.7490e-01, 4.0e-01, 6.0e-01);
   RooRealVar b0_DstarPBkg("b0_DstarPBkg","b0_DstarPBkg", 2.8914e+00, 2.0e+00, 4.0e+00);    
   x00_DstarPBkg.setConstant();
   a0_DstarPBkg.setConstant();
   b0_DstarPBkg.setConstant();
   RooFormulaVar x00prime_DstarPBkg("#x00prime_DstarPBkg", "x[0] < x[1] ? x[0] : x[1]", RooArgList(DeltaM, x00_DstarPBkg));     
   RooFormulaVar gamma0_DstarPBkg("#gamma0_DstarPBkg", "a0_DstarPBkg + 1", RooArgList(a0_DstarPBkg));    
   RooFormulaVar beta0_for_gamma_DstarPBkg("beta0_for_gamma_DstarPBkg", "1./b0_DstarPBkg", RooArgList(b0_DstarPBkg));    
   RooGamma GammaModel0_DstarPBkg("GammaModel0_DstarPBkg", "Gamma pdf", DeltaM, gamma0_DstarPBkg, beta0_for_gamma_DstarPBkg, x00prime_DstarPBkg);

   // Second Gamma Function
   RooRealVar x01_DstarPBkg("x01_DstarPBkg","x01_DstarPBkg", 1.3979e-01, 0.13, 0.15);
   RooRealVar a1_DstarPBkg("a1_DstarPBkg","a1_DstarPBkg", 3.0289e-01, 2.0e-01, 4.0e-01);
   RooRealVar b1_DstarPBkg("b1_DstarPBkg","b1_DstarPBkg", 1.0034e+02, 0.0, 500.);     
   x01_DstarPBkg.setConstant();
   a1_DstarPBkg.setConstant();
   b1_DstarPBkg.setConstant();
   RooFormulaVar x01prime_DstarPBkg("#x01prime_S", "x[0] < x[1] ? x[0] : x[1]", RooArgList(DeltaM, x01_DstarPBkg));     
   RooFormulaVar gamma1_DstarPBkg("#gamma1_DstarPBkg", "a1_DstarPBkg + 1", RooArgList(a1_DstarPBkg));    
   RooFormulaVar beta1_for_gamma_DstarPBkg("beta1_for_gamma_DstarPBkg", "1./b1_DstarPBkg", RooArgList(b1_DstarPBkg));    
   RooGamma GammaModel1_DstarPBkg("GammaModel1_DstarPBkg", "Gamma pdf", DeltaM, gamma1_DstarPBkg, beta1_for_gamma_DstarPBkg, x01prime_DstarPBkg);

   // Third Gamma Function
   RooRealVar x02_DstarPBkg("x02_DstarPBkg","x02_DstarPBkg", 1.3512e-01, 0.13, 0.15);
   RooRealVar a2_DstarPBkg("a2_DstarPBkg","a2_DstarPBkg", 2.2983e+00, 1.0e+00, 3.0e+00);
   RooRealVar b2_DstarPBkg("b2_DstarPBkg","b2_DstarPBkg", 1.5888e+01, 1.0e+01, 3.0e+01);     
   x02_DstarPBkg.setConstant();
   a2_DstarPBkg.setConstant();
   b2_DstarPBkg.setConstant();
   RooFormulaVar x02prime_DstarPBkg("#x02prime_S", "x[0] < x[1] ? x[0] : x[1]", RooArgList(DeltaM, x02_DstarPBkg));     
   RooFormulaVar gamma2_DstarPBkg("#gamma2_DstarPBkg", "a2_DstarPBkg + 1", RooArgList(a2_DstarPBkg));    
   RooFormulaVar beta2_for_gamma_DstarPBkg("beta2_for_gamma_DstarPBkg", "1./b2_DstarPBkg", RooArgList(b2_DstarPBkg));    
   RooGamma GammaModel2_DstarPBkg("GammaModel2_DstarPBkg", "Gamma pdf", DeltaM, gamma2_DstarPBkg, beta2_for_gamma_DstarPBkg, x02prime_DstarPBkg);

   // Add the components
   RooRealVar f0_DstarPBkg("f0_DstarPBkg", "f0", 1.9359e+00, 0, 2);
   RooRealVar f1_DstarPBkg("f1_DstarPBkg", "f1", 4.0209e-02, 0, 2);
   RooRealVar f2_DstarPBkg("f2_DstarPBkg", "f2", 1.3817e+00, 0, 2);
   // RooRealVar f3_DstarPBkg("f3_DstarPBkg", "f3", 1.7368e+00, 0, 2);
   f0_DstarPBkg.setConstant();
   f1_DstarPBkg.setConstant();
   f2_DstarPBkg.setConstant();
   // f3_DstarPBkg.setConstant();
   RooAddPdf CombBkgModel("CombBkgModel","g1+g2",RooArgList(GammaModel0_DstarPBkg,GammaModel1_DstarPBkg,GammaModel2_DstarPBkg), RooArgList(f0_DstarPBkg,f1_DstarPBkg,f2_DstarPBkg));

   // Total Model
   // Add the components
   RooRealVar f_DstarPBkg_Peak("f_DstarPBkg_Peak", "f0", 1.7470e-07, 0, 1);
   RooRealVar f_DstarPBkg_Comb("f_DstarPBkg_Comb", "f1", 3.9599e-04, 0, 1);
   f_DstarPBkg_Peak.setConstant();
   f_DstarPBkg_Comb.setConstant();
   RooAddPdf DstarPModel("DstarPModel","g1+g2",RooArgList(PeakingBkgModel,CombBkgModel), RooArgList(f_DstarPBkg_Peak,f_DstarPBkg_Comb));

   // Dstar0
   //------------------
   RooRealVar c0_Dstar0Bkg("c0_Dstar0Bkg", "coefficient #0", -3.0114e-01, -1.0, 1.0);
   RooRealVar c1_Dstar0Bkg("c1_Dstar0Bkg", "coefficient #1", -1.9245e-01, -1.0, 1.0);
   RooRealVar c2_Dstar0Bkg("c2_Dstar0Bkg", "coefficient #2",  1.5322e-01, -1.0, 1.0);
   RooRealVar c3_Dstar0Bkg("c3_Dstar0Bkg", "coefficient #3", -6.8649e-02, -1.0, 1.0);
   RooRealVar c4_Dstar0Bkg("c4_Dstar0Bkg", "coefficient #4",  4.9391e-02, -1.0, 1.0);
   RooRealVar c5_Dstar0Bkg("c5_Dstar0Bkg", "coefficient #5", -2.0065e-02, -1.0, 1.0);
   RooRealVar c6_Dstar0Bkg("c6_Dstar0Bkg", "coefficient #6",  1.9927e-03, -1.0, 1.0);
   RooRealVar c7_Dstar0Bkg("c7_Dstar0Bkg", "coefficient #7",  4.1666e-03, -1.0, 1.0);
   RooRealVar c8_Dstar0Bkg("c8_Dstar0Bkg", "coefficient #8", -6.0424e-03, -1.0, 1.0);
   c0_Dstar0Bkg.setConstant(true);
   c1_Dstar0Bkg.setConstant(true);
   c2_Dstar0Bkg.setConstant(true);
   c3_Dstar0Bkg.setConstant(true);
   c4_Dstar0Bkg.setConstant(true);
   c5_Dstar0Bkg.setConstant(true);
   c6_Dstar0Bkg.setConstant(true);
   c7_Dstar0Bkg.setConstant(true);
   c8_Dstar0Bkg.setConstant(true);
   RooChebychev Dstar0BkgModel("Dstar0BkgModel", "Dstar0BkgModel", DeltaM, RooArgList(c0_Dstar0Bkg,c1_Dstar0Bkg,c2_Dstar0Bkg,c3_Dstar0Bkg,c4_Dstar0Bkg,c5_Dstar0Bkg,c6_Dstar0Bkg,c7_Dstar0Bkg,c8_Dstar0Bkg));

   // D0
   //---------------
   RooRealVar c0_D0Bkg("c0_D0Bkg", "coefficient #0", -6.7830e-04, -1.0, 1.0);
   RooRealVar c1_D0Bkg("c1_D0Bkg", "coefficient #1", -3.7655e-01, -1.0, 1.0);
   RooRealVar c2_D0Bkg("c2_D0Bkg", "coefficient #2",  1.6824e-01, -1.0, 1.0);
   RooRealVar c3_D0Bkg("c3_D0Bkg", "coefficient #3", -2.1080e-02, -1.0, 1.0);
   RooRealVar c4_D0Bkg("c4_D0Bkg", "coefficient #4", -5.6988e-03, -1.0, 1.0);
   RooRealVar c5_D0Bkg("c5_D0Bkg", "coefficient #5",  1.4470e-02, -1.0, 1.0);
   RooRealVar c6_D0Bkg("c6_D0Bkg", "coefficient #6", -1.1129e-02, -1.0, 1.0);
   RooRealVar c7_D0Bkg("c7_D0Bkg", "coefficient #7",  1.0818e-02, -1.0, 1.0);
   RooRealVar c8_D0Bkg("c8_D0Bkg", "coefficient #8", -1.0832e-02, -1.0, 1.0);
   c0_D0Bkg.setConstant(true);
   c1_D0Bkg.setConstant(true);
   c2_D0Bkg.setConstant(true);
   c3_D0Bkg.setConstant(true);
   c4_D0Bkg.setConstant(true);
   c5_D0Bkg.setConstant(true);
   c6_D0Bkg.setConstant(true);
   c7_D0Bkg.setConstant(true);
   c8_D0Bkg.setConstant(true);
   RooChebychev D0BkgModel("D0BkgModel", "D0BkgModel", DeltaM, RooArgList(c0_D0Bkg,c1_D0Bkg,c2_D0Bkg,c3_D0Bkg,c4_D0Bkg,c5_D0Bkg,c6_D0Bkg,c7_D0Bkg,c8_D0Bkg));

   // Other
   //------------
   // First Gamma Function
   RooRealVar x00_FakeD0Bkg("x00_FakeD0Bkg","x00_FakeD0Bkg", 1.5792e-01, 0.13, 0.2);
   RooRealVar a0_FakeD0Bkg("a0_FakeD0Bkg","a0_FakeD0Bkg", 2.6847e-01, 2.0e-01, 4.0e-01);
   RooRealVar b0_FakeD0Bkg("b0_FakeD0Bkg","b0_FakeD0Bkg", 8.1515e+00, 7.0e+00, 9.0e+00);    
   x00_FakeD0Bkg.setConstant();
   a0_FakeD0Bkg.setConstant();
   b0_FakeD0Bkg.setConstant();
   RooFormulaVar x00prime_FakeD0Bkg("#x00prime_FakeD0Bkg", "x[0] < x[1] ? x[0] : x[1]", RooArgList(DeltaM, x00_FakeD0Bkg));     
   RooFormulaVar gamma0_FakeD0Bkg("#gamma0_FakeD0Bkg", "a0_FakeD0Bkg + 1", RooArgList(a0_FakeD0Bkg));    
   RooFormulaVar beta0_for_gamma_FakeD0Bkg("beta0_for_gamma_FakeD0Bkg", "1./b0_FakeD0Bkg", RooArgList(b0_FakeD0Bkg));    
   RooGamma GammaModel0_FakeD0Bkg("GammaModel1_FakeD0Bkg", "Gamma pdf", DeltaM, gamma0_FakeD0Bkg, beta0_for_gamma_FakeD0Bkg, x00prime_FakeD0Bkg);

   // Second Gamma Function
   RooRealVar x01_FakeD0Bkg("x01_FakeD0Bkg","x01_FakeD0Bkg", 1.3166e-01, 0.13, 0.2);
   RooRealVar a1_FakeD0Bkg("a1_FakeD0Bkg","a1_FakeD0Bkg", 3.8644e+00, 3.0e+00, 5.0e+00);
   RooRealVar b1_FakeD0Bkg("b1_FakeD0Bkg","b1_FakeD0Bkg", 1.6837e+01, 1.0e+01, 3.0e+01);     
   x01_FakeD0Bkg.setConstant();
   a1_FakeD0Bkg.setConstant();
   b1_FakeD0Bkg.setConstant();
   RooFormulaVar x01prime_FakeD0Bkg("#x01prime_S", "x[0] < x[1] ? x[0] : x[1]", RooArgList(DeltaM, x01_FakeD0Bkg));     
   RooFormulaVar gamma1_FakeD0Bkg("#gamma1_FakeD0Bkg", "a1_FakeD0Bkg + 1", RooArgList(a1_FakeD0Bkg));    
   RooFormulaVar beta1_for_gamma_FakeD0Bkg("beta1_for_gamma_FakeD0Bkg", "1./b1_FakeD0Bkg", RooArgList(b1_FakeD0Bkg));    
   RooGamma GammaModel1_FakeD0Bkg("GammaModel2_FakeD0Bkg", "Gamma pdf", DeltaM, gamma1_FakeD0Bkg, beta1_for_gamma_FakeD0Bkg, x01prime_FakeD0Bkg);

   // Third Gamma Function
   RooRealVar x02_FakeD0Bkg("x02_FakeD0Bkg","x02_FakeD0Bkg", 3.7183e-01, 0.13, 0.5);
   RooRealVar a2_FakeD0Bkg("a2_FakeD0Bkg","a2_FakeD0Bkg", 2.7283e+01, 2.0e+01, 4.0e+01);
   RooRealVar b2_FakeD0Bkg("b2_FakeD0Bkg","b2_FakeD0Bkg", 1.7067e+02, 1.0e+02, 3.0e+02);     
   x02_FakeD0Bkg.setConstant();
   a2_FakeD0Bkg.setConstant();
   b2_FakeD0Bkg.setConstant();
   RooFormulaVar x02prime_FakeD0Bkg("#x02prime_S", "x[0] < x[1] ? x[0] : x[1]", RooArgList(DeltaM, x02_FakeD0Bkg));     
   RooFormulaVar gamma2_FakeD0Bkg("#gamma2_FakeD0Bkg", "a2_FakeD0Bkg + 1", RooArgList(a2_FakeD0Bkg));    
   RooFormulaVar beta2_for_gamma_FakeD0Bkg("beta2_for_gamma_FakeD0Bkg", "1./b2_FakeD0Bkg", RooArgList(b2_FakeD0Bkg));    
   RooGamma GammaModel2_FakeD0Bkg("GammaModel3_FakeD0Bkg", "Gamma pdf", DeltaM, gamma2_FakeD0Bkg, beta2_for_gamma_FakeD0Bkg, x02prime_FakeD0Bkg);

   // Add the components
   RooRealVar f0_FakeD0Bkg("f0_FakeD0Bkg", "f0", 1.0592e+00, 0.5e+00, 2.0e+00);
   RooRealVar f1_FakeD0Bkg("f1_FakeD0Bkg", "f1", 9.6705e-01, 9.0e-01, 11.0e-01);
   RooRealVar f2_FakeD0Bkg("f2_FakeD0Bkg", "f2", 9.9090e-02, 9.0e-02, 11.0e-02);
   f0_FakeD0Bkg.setConstant();
   f1_FakeD0Bkg.setConstant();
   f2_FakeD0Bkg.setConstant();
   RooAddPdf OtherModel("OtherModel","g1+g2",RooArgList(GammaModel0_FakeD0Bkg,GammaModel1_FakeD0Bkg,GammaModel2_FakeD0Bkg), RooArgList(f0_FakeD0Bkg,f1_FakeD0Bkg,f2_FakeD0Bkg));
   
   //--------------- Combined Model of signal and generic MC ------------------//
   //--------------------------------------------------------------------------//
   RooRealVar f0("f0", "f0", 0, -100., 100.);
   RooRealVar f1("f1", "f1", 9.0157e+04, 8.0e+04, 10.0e+04);
   RooRealVar f2("f2", "f2", 1.7312e+05, 1.0e+05, 3.0e+05);
   RooRealVar f3("f3", "f3", 7.0367e+04, 6.5e+04, 7.5e+04);
   RooRealVar f4("f4", "f4", 4.9844e+03, 4.0e+03, 5.0e+03);

//    RooRealVar f1("f1", "f1", 8.6566e+04, 8.0e+04, 9.0e+04);
//    RooRealVar f2("f2", "f2", 1.7539e+05, 1.0e+05, 2.0e+05);
//    RooRealVar f3("f3", "f3", 7.2617e+04, 7.0e+04, 8.0e+04);
//    RooRealVar f4("f4", "f4", 4.0214e+03, 3.5e+03, 4.5e+05);
   // f0.setConstant(true);
   // f1.setConstant(true);
   // f2.setConstant(true);
   // f3.setConstant(true);
   // f4.setConstant(true);
   // RooAddPdf model("model", "s+pbkg+cbkg+fs", RooArgList(SignalModel,PeakingBkgModel,CFBkgModel,FakeSignalModel,OtherModel), RooArgList(f0,f1,f2,f3,f4));
   // RooAddPdf model("model", "s+pbkg+cbkg+fs", RooArgList(*SignalModel,*DstarPModel), RooArgList(f0,f1));
   // RooAddPdf model("model", "s+pbkg+cbkg+fs", RooArgList(*SignalModel,*Dstar0BkgModel), RooArgList(f0,f2));
   // RooAddPdf model("model", "s+pbkg+cbkg+fs", RooArgList(*SignalModel,*D0BkgModel), RooArgList(f0,f3));
   // RooAddPdf model("model", "s+pbkg+cbkg+fs", RooArgList(*SignalModel,*OtherModel), RooArgList(f0,f4));
   // RooAddPdf model("model", "s+pbkg+Dstar0+D0+fD0", RooArgList(*DstarPModel,*Dstar0BkgModel,*D0BkgModel,*OtherModel), RooArgList(f1,f2,f3,f4));
   // RooAddPdf model("model", "s+pbkg+Dstar0+D0+fD0", RooArgList(*SignalModel,*DstarPModel,*Dstar0BkgModel,*D0BkgModel,*OtherModel), RooArgList(f0,f1,f2,f3,f4));
   RooAddPdf model("model", "s+pbkg+Dstar0+D0+fD0", RooArgList(SignalModel,DstarPModel,Dstar0BkgModel,D0BkgModel,OtherModel), RooArgList(f0,f1,f2,f3,f4));
   //=========================================================================================================================================================================//
   // S e t   t h e   C o n s t a n t   f o r   t h e    V a r i a b l e s
   //--------------------------------------------------------------------------
   // The code below fixes the value for a certain value.
   // f0.setVal();
   // f1.setVal();
   // f2.setVal();

   // The code below removes the range and fixes the value.
   // f0.setConstant(true);
   // f1.setConstant(true);
   // f2.setConstant(true);

   // DeltaM.setVal(0.325);
   // DeltaM.setConstant(true);
   //=========================================================================================================================================================================//
   // F i t
   //-------------
   
   // Construct unbinned likelihood of model w.r.t. data
   std::unique_ptr<RooAbsReal> nll{model.createNLL(*filteredData)};

   // Create MINUIT interface object
   RooMinimizer m(*nll);

   // Activate verbose logging of MINUIT parameter space stepping
   m.setVerbose(false);

   // Call MIGRAD to minimize the likelihood
   m.migrad();

   // Print values of all parameters, that reflect values (and error estimates)
   // that are back propagated from MINUIT
   std::unique_ptr<RooArgSet>{model.getParameters(DeltaM)}->Print("s");

   // Disable verbose logging
   m.setVerbose(false);
 
   // Run HESSE to calculate errors from d2L/dp2
   m.hesse();
 
   // Print value (and error) of sigma_g2 parameter, that reflects
   // value and error back propagated from MINUIT
   f0.Print();
 
   // Run MINOS on sigma_g2 parameter only
   m.minos(f0);
 
   // Print value (and error) of sigma_g2 parameter, that reflects
   // value and error back propagated from MINUIT
   f0.Print();

   // Save a snapshot of the fit result. This object contains the initial
   // fit parameters, the final fit parameters, the complete correlation
   // matrix, the EDM, the minimized FCN , the last MINUIT status code and
   // the number of times the RooFit function object has indicated evaluation
   // problems (e.g. zero probabilities during likelihood evaluation)
   std::unique_ptr<RooFitResult> fitResult{m.save()};
   //=========================================================================================================================================================================//
   // === Contour Plot Section ===
   TCanvas* c_contour = new TCanvas("c_contour", "Contour Plots", 2000, 1600);
   c_contour->Divide(5, 4);

   std::vector<std::pair<RooRealVar*, RooRealVar*>> pairs = {
      {&f0, &f1}, {&f0, &f2}, {&f0, &f3}, {&f0, &f4},
      {&f1, &f2}, {&f1, &f3}, {&f1, &f4},
      {&f2, &f3}, {&f2, &f4},
      {&f3, &f4}
   };

   int idx = 1;
   for (const auto& p : pairs) {
      c_contour->cd(idx);
      RooPlot *frame = m.contour(*p.first, *p.second, 1, 2, 3);
      frame->SetTitle(Form("%s vs %s", p.first->GetName(), p.second->GetName()));
      frame->Draw();
      ++idx;
   }

   c_contour->SaveAs("/home/belle2/amubarak/Ds2D0enue_Analysis/10-Suggestion/Roofit_Suggestion_Likehood_Window/Fit_Image/rs10_Contours.png");

}